### ISSUE TITLE
Decouple opengl/rendering from widgets/core

### ISSUE THREAD

**Issue by dpwiz** [fjvallarino/monomer#10]
I don't know how deep the current connection goes, but I would be glad to reuse the application framework with different (vulkan, glfw, etc.) renderer.

**Comment by fjvallarino** [comment]
Hi @dpwiz! 

The library has a [Renderer](https://github.com/fjvallarino/monomer/blob/main/src/Monomer/Graphics/Types.hs#L246) abstraction that is used by widgets for all rendering related operations. Currently, there is only one implementation based on NanoVG, although other implementations could be added. I recently added this section to [Design decisions](https://github.com/fjvallarino/monomer/blob/main/docs/design-decisions.md#why-nanovg-the-projects-repository-says-its-not-actively-maintained) that could be of interest, especially for the alternative renderer ideas.

Regarding GLFW, I think that one is going to be much harder. Originally I wanted to abstract SDL to be able to replace it with a different library (GLFW in particular), but it turned out to be complex, and I didn't feel it provided much value for what I needed at that point (plus I'd like to support mobile someday, which GLFW does not handle). At this point, Monomer is pretty much tied to SDL2.

#### Note regarding mixing lower-level rendering code

While still using the current NanoVG implementation, in your widget's render function, you can call `createRawTask`; the action provided to this function will be run outside the context of NanoVG. Since NanoVG uses OpenGL, this means you will be able to run any OpenGL command you want (and also means you have to take care of setting everything up, including shaders). Raw tasks are executed after rendering regular widgets (it's a separate rendering pass).

I don't currently have an example at hand, and it's been a while since I last tested this, so weird issues may happen that I'm unaware of.

**Comment by dpwiz** [comment]
Hmm. Building on DearImGui is an interesting venue - opens up many different backends.

**Comment by dpwiz** [comment]
The polymorphic event story is a mess, I agree. I, too, decided to ditch it for now, in my engine and stuck with glfw instead.

**Comment by fjvallarino** [comment]
Just to clarify, the widgets are agnostic to SDL2. They handle events and requests using Monomer's types and functions. 

What I mean when I say that it is tied to SDL2 is that the internals, which are not visible to library users, are programmed directly using SDL2 functions instead of using some abstraction. This is contrary to what happens with Renderer, which can be swapped for a different one.

**Comment by fjvallarino** [comment]
@dpwiz I'll close this issue for the time being. If you have any other questions or issues, don't hesitate to re-open it or create a new one. Thanks!

**Comment by dpwiz** [comment]
BTW, I've added most of the DrawList methods to [dear-imgui](https://github.com/haskell-game/dear-imgui.hs) bindings.

There are some event/input related functions I need to investigate, they might provide that cross-framework platform.

**Comment by fjvallarino** [comment]
@dpwiz nice! I'll take a look. My main concern is I'm relying on quite a few NanoVG features:

- Painting with a texture inside an arbitrary path (can be seen when setting rounded corners on an image widget)
- General curves (bezier, quadratic, etc), which are rendered pretty nicely.

I have to check how hard it is to get the same out of ImGUI's DrawList.

**Comment by dpwiz** [comment]
`DrawList`s have both textures with rounded corners and straight/smooth paths.
