### ISSUE TITLE
hstack problem

### ISSUE THREAD

**Issue by prolic** [fjvallarino/monomer#115]
This might not be an issue, but I definitely ran into this and am kind of stuck:

Considering this hstack:
```
hstack [
        button "Back" Back,
        spacer,
        label "Mike wrote:" `styleBasic` [width 100],
        spacer,
        label "Here is something that Mike wrote"
      ] `styleBasic` [cursorHand, textTop]
```

The text is NOT aligned on top and the back button is huge. I tried adding `styleBasic [height 20]`  to the back button without success.

Any help is appreciated

![Screenshot_20220411_230007](https://user-images.githubusercontent.com/394428/162870759-d22aae06-ae5c-458d-8e4c-cd1fc37c8868.png)

**Comment by prolic** [comment]
Also, is there a way to make text "copy-able"?

**Comment by fjvallarino** [comment]
Hi @prolic!

Below you will find the updated code; here are the answers:

- The styles are not cascading as in CSS; they belong to the widget to which they are assigned. To avoid duplication, you can always use a function to standardize how you style things, as described [here](https://github.com/fjvallarino/monomer/blob/main/docs/tutorials/02-styling.md).
- Buttons, by default, have a hand cursor; it's not necessary to add it explicitly.
- The stack widgets assign space as requested in the axis they work in (vstack vertically, hstack horizontally) and then assign all the available space in the secondary axis (i.e., hstack will allocate all vertical space). This is better explained [here](https://github.com/fjvallarino/monomer/blob/main/docs/tutorials/01-basics.md#layout). In short, since `hstack` is the top-level widget, the whole window gets assigned to its immediate children. You can wrap it with a `vstack` so it only receives as much vertical space as its children request.
- There is not a selectable `label`, but you can emulate it using a read-only `textField`. The example below relies on the `textFieldD_` constructor, which is generally not used directly, to provide a value and avoid providing an `onChange` event (when using `textFieldV` you are forced to provide an event). I'll make notes to better document this.

```haskell
  widgetTree = vstack [
      hstack [
        button "Back" Back,
        spacer,
        label "Mike wrote:"
          `styleBasic` [width 100, textTop],
        spacer,
        textFieldD_ (WidgetValue "Here is something that Mike wrote") [readOnly]
      ]
    ]
```

**Comment by fjvallarino** [comment]
I just realized that you will need to use the latest version from `main` for the read-only `textFieldD_` idea to work. You can update your `stack.yaml` with:

```yaml
- git: https://github.com/fjvallarino/monomer.git
  commit: fc40e2e4df47b9d9f3873259f261e4180043d0f6
```

**Comment by prolic** [comment]
perfect, thanks my friend.

**Comment by prolic** [comment]
BTW: The text-field solution has some problems style-wise. I tried removing the border and radius and also set the background color manually, so it doesn't look like a text-field, but like a normal label:
```
    `styleBasic`
                    [ border 0 (Color 255 255 255 1.0)
                    , radius 0
                    , bgColor $ rgbHex "#515151"
                    ]
```
Problem is, I see some white lines:
![Screenshot_20220414_000425](https://user-images.githubusercontent.com/394428/163311577-784aa5e2-636e-4c4e-b65f-044a776ff8ed.png)
(Notice the 2 small white dashes below)

**Comment by fjvallarino** [comment]
I could not reproduce the issue. Could you paste your complete code? I tried this:

```haskell
  widgetTree = vstack [
      hstack [
        button "Back" AppInit,
        spacer,
        --label "Mike wrote:"
        --  `styleBasic` [width 100, textTop],
        spacer,
        filler,
        textFieldD_ (WidgetValue "Here is something that Mike wrote") [readOnly]
          `styleBasic` [
            border 0 (Color 255 255 255 0), -- could use transparent
            radius 0,
            bgColor $ rgbHex "#515151"
          ]
      ]
    ]
```

Notice that I used 0 for the last `Color` argument (alpha). There is also an exported `transparent` Color that you can use instead.

**Comment by prolic** [comment]
Right now I can't reproduce either. No idea. But it works now. Thanks for the hint to `transparent`.
