### ISSUE TITLE
Enter key and buttons

### ISSUE THREAD

**Issue by sproott** [fjvallarino/monomer#120]
When I press Enter, the last focused button gets pressed. Can this be disabled if I want to have a custom event bound to Enter?

**Comment by fjvallarino** [comment]
I'm not sure I understand. Does the button still have focus?

You can avoid having the event passed down to children when it matches a keystroke pattern by using [ignoreChildrenEvts](https://hackage.haskell.org/package/monomer/docs/Monomer-Widgets-Containers-Keystroke.html).

The problem is that, if the `button` is a child of `keystroke`, it will never receive the Enter event itself. In general, when I want to have a handler for `Enter`, I organize the tree in such a way that buttons are not children of `keystroke`. It may require using more than one instance of `keystroke` to achieve it, though; extracting the keystroke definition into a reusable function is a good idea if all patterns/events are the same.

**Comment by sproott** [comment]
The weird thing is that the buttons have actually been receiving the Enter event. But I recall it working as you say a while back. Could it be a regression from #117?

**Comment by fjvallarino** [comment]
If you have a code sample where I can reproduce the issue, I can check it.

**Comment by sproott** [comment]
Alright, I'll try to cook something up.

**Comment by sproott** [comment]
https://github.com/sproott/monomer-enter-key-test

Right after launching this example, just pressing Enter activates both the button press and the keystroke event.

**Comment by fjvallarino** [comment]
Applying the `ignoreChildrenEvts` config to `keystroke`, the Enter event is not passed to the `button`. You can still click on the button to trigger its event, but the Enter keypress will never reach it.

```haskell
buildUI :: WidgetEnv AppModel AppEvent -> AppModel -> WidgetNode AppModel AppEvent
buildUI wenv model = widgetTree where
  widgetTree = keystroke_ [("Enter", AEEnter)] [ignoreChildrenEvts] $
    button "Press me" AEButton
```

**Comment by sproott** [comment]
Oh then I probably misunderstood, so to actually do this, you do need ignoreChildEvts.

**Comment by fjvallarino** [comment]
I will add a note in the docs to be more explicit about it. Thanks!
