### ISSUE TITLE
Why is there no alignment config option for stack?

### ISSUE THREAD

**Issue by MuhammedZakir** [fjvallarino/monomer#140]
Currently, we can do it in (at least) 2 ways:
```haskell
-- Doubt: This works, but is this "okay"?
vstack [
  filler
, label "a label"
, filler
]
```
OR
```haskell
box_ [alignCenter] $ vstack [
  label "a label"
]
```

But it would be nice if we can do:
```haskell
vstack_ [alignCenter] [
  label "a label"
]
```

I guess implementing vertical alignment for `hstack` and horizontal alignment for `vstack` would be easier? As it is kind of like adding a `filler` on both sides.

For `zstack`, we will need both horizontal and vertical alignment. For example, to overlay a text over image and making them centered. However, if this causes unnecessary complexities, maybe it's better not to add it.

**Comment by fjvallarino** [comment]
It does not have it by design. The idea is that each layout widget does a single thing and can be combined to create more complex layouts.

In the particular case of `hstack` and `vstack` widgets, they assign space based on what the child widgets request and only ask for as much space as needed to satisfy those requirements. Since they assign space based on what was requested, they don't have a concept of free space they can use for centering.

**Comment by MuhammedZakir** [comment]
That make sense. I will just create some functions that wrap `stack` with `box`. That works for me. You could maybe add those as "utility" functions? However, you probably only need to care about this if the usecase is high or more users ask this.

---

Maybe it's because I am not _that_ familiar with this -- I was tripped by "if the box has extra free space". After thinking about it, I understood what you meant. But IMHO, practically, we usually only need to care about alignment when there is free space. Just saying as these might trip newbies like me. :-)

**Comment by fjvallarino** [comment]
It depends on what kind of utility functions. If it is something that would be painful for users to add themselves, I think it belongs in the library. Otherwise, I avoid adding them for a few reasons:

- What is helpful for some people may not valuable for others.
- Discovering utility functions becomes harder as their number increases.
- Anything you expose from a library is problematic to change or remove afterward.

In the specific case of the alignment helpers you mention, I feel that it is something that belongs in the application. The `box` widget has several other configuration options and even allows combining the alignment options (i.e., right-bottom). A utility function would hide those options, which may be great for one programmer but maybe not for others.

---

Documentation is the main topic I will work on for the next release. There will not be many features added, only a few things that will allow me to introduce some concepts that have remained unexplained. Anyway, I think documenting the project works better as an iterative process and will not be done in a single release, since there is always something to improve (beyond documenting new features).

**Comment by MuhammedZakir** [comment]
Understood and agreed.

Regarding doc: feel free to ping me for proofreading. I will do what I can.
