### ISSUE TITLE
[Help] How to create a new window?

### ISSUE THREAD

**Issue by MuhammedZakir** [fjvallarino/monomer#143]
I need to create a new window when a button in the window or menu[1] is clicked.

[1] Is menu not implemented? I couldn't find that in the doc.

**Comment by fjvallarino** [comment]
Multi-window is not currently supported; I haven't thought about how to structure an application that uses it. Who receives the events? Are there multiple widget roots?

The library leans mostly toward single-window development. Partly because I'm biased toward that type of development since I worked for a long time in web and mobile, but mainly because the intention is to provide a core that works well in all the supported platforms (the plan is to, at some point, support mobile).

---

There is not currently a menu widget. In general I have used vstack/hstack and buttons/labels for navigation, in some cases showing a side menu overlaid with zstack. One widget I will be merging to main soon is `popup`, which temporarily shows a widget on top of the active content. The popup widget could be used in a menu where clicking on an item displays more options.

This widget would work well as something that can be created in the tutorials to show some of the Composite features I want to show. If it turns out nicely, it can become part of the core library (or part of a contrib, non-core, package). I'll look into it.

**Comment by MuhammedZakir** [comment]
> Multi-window is not currently supported; I haven't thought about how to structure an application that uses it. Who receives the events? Are there multiple widget roots?

Something like:

- a window is a special widget which can contain everything but itself.
- only one window in an application can have focus at a time.
- the windows can communicate between each other using messages.
    - plausibly will need a scope, otherwise we will have to use a unique event ids. If the latter makes implementation easier, I am fine with it.
    - maybe use the main window (the one started using `startApp`(?)) as the root window of all other windows if that makes managing events easier. Kind of like parent<->child widgets.

> The library leans mostly toward single-window development. Partly because I'm biased toward that type of development since I worked for a long time in web and mobile, but mainly because the intention is to provide a core that works well in all the supported platforms (the plan is to, at some point, support mobile).

I see. I will try using `zstack`. I chose `window` because most of the time, only one `window` will be active. I was wondering if `zstack` may cause problems as this app could be used in a low-end desktop [1]. Anyway, I will give that a try.

[1] Mainly, does `zstack` render every child widget even if some of them is not `visible`. Or more specifically, if a widget is not `visible`, is it rendered?

---

> There is not currently a menu widget. In general I have used vstack/hstack and buttons/labels for navigation, in some cases showing a side menu overlaid with zstack. One widget I will be merging to main soon is `popup`, which temporarily shows a widget on top of the active content. The popup widget could be used in a menu where clicking on an item displays more options.

I assume this widget can contain arbitrary sized widgets? So I can emulate a window, or create a custom alert, choice etc.?

> This widget would work well as something that can be created in the tutorials to show some of the Composite features I want to show. If it turns out nicely, it can become part of the core library (or part of a contrib, non-core, package). I'll look into it.

Will be waiting. :-)

**Comment by fjvallarino** [comment]
The main idea with `popup` is showing _temporary_ content, so notifications and alerts are a good fit, but windows may not work well.  The reason is popup is an overlay, and there is a maximum of one active overlay at a time (this will be explained better in the accompanying docs).

If you want to manage application windows that you can drag inside the main OS window, the best route is probably creating a custom `Container` that takes care of layout.

The good thing is you can get away without using overlapping/draggable windows in many cases. Ableton Live is a great example of how effective a single window can be.

---

As you mention, zstack is a great alternative for what you want to do! There is no performance penalty for using it if the inactive layers are hidden since they will not be rendered or process events (and will usually not receive events if they are not the top layer).

I created a small example of things you can do with zstack for layout purposes (maybe I can it in a _recipes_ section I'm planning). There are a few comments in the code that could be helpful.

```haskell
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TemplateHaskell #-}

module Main where

import Control.Lens
import Monomer
import TextShow

import qualified Monomer.Lens as L

data AppModel = AppModel {
  _sideBarVisible :: Bool,
  _maxSections :: Int,
  _activeSection :: Int
} deriving (Eq, Show)

data AppEvent
  = AppInit
  | ShowSection Int
  deriving (Eq, Show)

makeLenses 'AppModel

buildUI
  :: WidgetEnv AppModel AppEvent
  -> AppModel
  -> WidgetNode AppModel AppEvent
buildUI wenv model = widgetTree where
  sideBarBg = wenv ^. L.theme . L.sectionColor
  sectionIds = [1 .. model ^. maxSections]

  {-
  This could even be a button, since they support focus and can be navigated with
  the keyboard. The 'ignoreTheme' config could be useful to reset styling (remove
  borders, etc).
  -}
  sectionSelector sectionIdx = selector where
    item = label ("Section " <> showt sectionIdx)
      `styleHover` [textColor lightSkyBlue]

    selector = box_ [alignLeft, onClick (ShowSection sectionIdx)] item
      `styleBasic` [cursorHand]

  sectionBody sectionIdx = item where
    cfgs = [alignCenter, alignMiddle]
    item = box_ cfgs (label $ "This is section " <> showt sectionIdx)
      `styleBasic` [minWidth 100, minHeight 100]
      `nodeVisible` (model ^. activeSection == sectionIdx)

  sideBarToggle = toggleButton "Toggle side bar" sideBarVisible

  sideBar = item where
    children = vstack_ [childSpacing] $
      sectionSelector <$> sectionIds

    layout = vstack [
        sideBarToggle,
        spacer,
        children
      ]
      `styleBasic` [width 200, minHeight 100, padding 10, bgColor sideBarBg]

    item = box_ [alignLeft, ignoreEmptyArea] layout

  menuBar = hstack [
      hstack_ [childSpacing] (sectionSelector <$> sectionIds),
      spacer,
      sideBarToggle
    ]

  mainContent = vstack_ [childSpacing] [
      menuBar,
      vstack (sectionBody <$> sectionIds)
    ]

  {-
  You can toggle 'onlyTopActive' (or even remove it) to avoid events reaching the
  bottom layer when the side bar is open.
  -}
  widgetTree = zstack_ [onlyTopActive_ False] [
      mainContent,
      sideBar
        `nodeVisible` model ^. sideBarVisible
    ] `styleBasic` [padding 10]

handleEvent
  :: WidgetEnv AppModel AppEvent
  -> WidgetNode AppModel AppEvent
  -> AppModel
  -> AppEvent
  -> [AppEventResponse AppModel AppEvent]
handleEvent wenv node model evt = case evt of
  AppInit -> []
  ShowSection section -> [
    Model $ model
      & activeSection .~ section
      -- Uncommenting this line causes the side bar to close when a section is selected
      -- & sideBarVisible .~ False
    ]

main :: IO ()
main = do
  startApp model handleEvent buildUI config
  where
    config = [
      appWindowTitle "Menus and layouts",
      appWindowIcon "./assets/images/icon.bmp",
      appTheme darkTheme,
      appFontDef "Regular" "./assets/fonts/Roboto-Regular.ttf",
      appInitEvent AppInit
      ]
    model = AppModel {
      _sideBarVisible = False,
      _maxSections = 5,
      _activeSection = 1
    }
```

**Comment by MuhammedZakir** [comment]
That does seem to solve my problem. I highly recommend to add this to the "recipes". These kind of stuff really helps to get started with this and to get an idea of the capilities.

---

About menu widget: I was hoping that this could integrate with OS and mimic rest of the apps. E.g. macOS menubar and underline a letter when `Alt` is pressed.

**Comment by fjvallarino** [comment]
I took a look at the issue of missing system menus, but it seems SDL2 does not have support for them.

There is a mention in [this issue](https://discourse.libsdl.org/t/support-for-system-style-menus/22082/4) about how they could be manually implemented, but I'm not going to pursue it for now.

**Comment by fjvallarino** [comment]
Nothing is pending in this issue now, so I'll close it. Please re-open or create a new one if you think something is missing.

If SDL implements the menu functionality, or if I find a library that I can import into the existing structure and supports cross-platform system menu bars, I'll implement it.

**Comment by MuhammedZakir** [comment]
About multiple windows: is it that you won't implement it, or you haven't though about how to implement it? What you said above and the example you gave is (hopefully) enough for me to built he current app, but there are some apps you will *need* multiple windows. Especially if the client wants that, nothing I can do about that. This is the only thing I *actually* find missing.

I looked into `Containers` and I think I could emulate a window by referring to `Draggable`'s code. But what is missing is, or what I need is window decoration/buttons (minimize, maximize & close).

P.S. At least for now, for me, this is not a high-priority issue.

> If SDL implements the menu functionality, or if I find a library that I can import into the existing structure and supports cross-platform system menu bars, I'll implement it.

Okay.

**Comment by fjvallarino** [comment]
It's a problem of time. Do I want to support multiple windows? Sure, absolutely. But it's not a priority for me now, and it will be long before I can look into it. I feel that if I keep an open issue around, it will give a false impression that I will work on it shortly; I think answering the question each time it arises is clearer, but probably I'm wrong.

My current objectives are improving what the library already offers and enhancing the documentation, with bug fixes getting absolute priority. Once I feel the documentation is good enough and the library is stable (which will take a few months), I will move into making it work on mobile; this is the main reason for me to give multi-window low priority.

**Comment by MuhammedZakir** [comment]
Understood. When I asked this, I was hoping this wouldn't be hard to implement by implementing them as/like composite widgets and because SDL already supports multiple windows. I guess I simplified it too much.
