### ISSUE TITLE
[Build] When building monomer library, don't build executables by default

### ISSUE THREAD

**Issue by MuhammedZakir** [fjvallarino/monomer#155]
IMHO, this feels unnecessary especially when building it as a dependency.

**Comment by fjvallarino** [comment]
Added an `examples` flag to only build examples and tutorial when request:

```bash
stack build --flag monomer:examples
```

A small application (`dev-test-app`) is still built with the library, since it simplifies the testing process. This is explained in the associated PR: https://github.com/fjvallarino/monomer/pull/218.

I'll close the issue for the time being. Please re-open or create a new one if needed. Thanks!
