### ISSUE TITLE
Pull Request?

### ISSUE THREAD

**Issue by MilesLitteral** [fjvallarino/monomer#165]
Hi Vallarino, I made a change to Monomer to help ease the use of OS specific dialogs (like choosing a file, folder, system message popups) while staying OS-agnostic in function. 

Is there a standard for submitting pull requests to this project? Otherwise I can make a repo and open a PR if you are interested in the feature

**Comment by fjvallarino** [comment]
I @MilesLitteral!

I answered the PR.

The process you followed is correct: checking with an issue first, then submitting the PR. Unfortunately, I could not answer in time.

I think showing this as an example would be great since other users might be interested in using OS-specific dialog boxes. I'll add it to the recipes when it's available.
