### ISSUE TITLE
Tooltips won't easily go away

### ISSUE THREAD

**Issue by prolic** [fjvallarino/monomer#167]
See attached video to show the problem.

https://user-images.githubusercontent.com/394428/173157037-12bc1031-33be-43a5-a82a-3bdef564e6aa.mp4

**Comment by fjvallarino** [comment]
I pushed a PR with an improvement, but I can't completely replicate your scenario.

I created an example that:

- Has two layers managed with `zstack`.
- The bottom layer has a button that shows the top one (which is invisible initially), and the top one has a button that hides it again.
- The button on the bottom layer has a tooltip. When the tooltip is visible and the button is clicked, the tooltip is still displayed even when the top layer is displayed (this is wrong and fixed in the PR).

However, I can't replicate what you show in the video about the accumulating tooltips:

- Without the fix: as soon as I move the mouse on the top layer, the tooltip disappears.
- With the fix: the tooltip closes as soon as I press the button.

Do you have a minimal example I can try which reproduces the complete issue? Of course, if the PR fixes the issue for you, this is not needed.

**Comment by prolic** [comment]
Your PR fixes the problem, thank you
