### ISSUE TITLE
Question regarding handling of incoming websocket data

### ISSUE THREAD

**Issue by prolic** [fjvallarino/monomer#179]
My scenario is this:

1. A websocket connection is created that constantly receives new data.
2. I have a few different widgets with its own model, that all need access to the same data that is coming from websockets.

Question:

1. Does it make sense to put websocket data away in a "Home Widget" to have the `Main` more clean? Or would event handlers get disposed as well, as soon as I go away and come back to home and I'm better off handling the websockets in Main?
2. What's the best way to pass the websocket data along all widgets that need access? It's kind of messy to insert new data not only to the main model, but also two a bunch of submodels or even submodels of submodels. Also doesn't this bloat my memory a lot, when I need to store basically the same data in 5 different places?

**Comment by fjvallarino** [comment]
I don't have hard answers for this. These are mostly design decisions, each with its pros and cons that you have to make on a per-project basis. What comes next is my opinion, and it's best if taken as just that, an opinion.

### Connection lifecycle

If the connection will be active during the complete application's lifetime, I would put it at the highest level possible. In most cases this is `Main`, but if you have a sub-widget of `Main` that will not be removed during the application's lifetime, it can work well too.

### Model sharing

Note: I'm assuming all your widgets are Composites because of the mention of multiple models.

In the same way you can pass a lens to a `Text` field to `textField`, you can pass as many lenses as you need to your child Composites since they can consume a part of their parent's model (they don't need to be isolated). Sometimes you just want to split the UI into separate chunks that are easier to manage with an independent event queue, but you don't need the model to be isolated from the application. In this case, you could have:

```haskell
data Message = Message { .. }

data ChildModel = ChildModel { ... }

data ParentModel = ParentModel {
   _pmUser :: User
   _pmMessages :: Seq Message,
   _pmChildModel :: ChildModel
}
```

Then, when you declare an instance of `childWidget`, you can pass `messages` and `childModel` and consume the data directly from the parent's model.

This works well for direct `parent -> child` relationships. If you want to go one level further, you need to ensure the grandchild's model is inside `_pmChildModel`. Suppose you instead have `_pmGrandChildModel` inside `ParentModel`. In that case, the types will not match when creating the `grandChildWidget` instance because you need a lens from `ParentModel`, but your context would be a `ChildModel`.

This will work well, but you need to consider that Composites only rebuild their UI when the model changes, so each widget (parent, child, and grandchild) will be looking at ParentModel, ChildModel, and GrandChildModel, respectively. The problem is, you also want them to look at `messages`. For the parent, this is fine since it's part of its model, and you can use `mergeRequired` in child, but you'll face the same type mismatch issue if you try to do it in grandChild. You could pass a flag argument or something similar to make it work, but you would be coupled to a component two levels above yours.

In my opinion, you are better off just having the information you need at hand, which means having messages as part of each model. Depending on how the data is structured, you can update each model directly when a websocket message is received (only valid in the nested model case) or use `compositeMergeModel` in each child widget (both for nested models or isolated ones).

### Passing curried arguments to widgets

An alternative I sometimes use is passing down an extra `AppEnv` argument, but I only do this for data that does not change (database connections or similar).

```haskell
childWidget appEnv field = composite "child" field uiBuilder eventHandler where
  -- buildUI receives appEnv wenv model, but is used curried. Same for handleEvent
  uiBuild = buildUI appEnv
  eventHandler = handleEvent appEnv
```

### Memory usage

If you store the messages in a list or `Seq`, and all widgets receive the same reference, no extra memory will be used.

### You may not always need Composite

In many cases, you can get away without using Composite. For example, you could do:

```haskell
data ChildEvt
  = ChildEvt1

data ParentEvt
  = AddUser
  | ChildEvent ChildEvt

handleChildEvt wenv node target evt = ...

handleEvent wenv node target evt = case evt of
   AddUser -> [ ... ]
   ChildEvent cevt = handleChildEvt wenv node target evt

buildChildUI wenv model = button "Test" (ChildEvent ChildEvt1)

buildUI wenv model = vstack [
    button "Add user" AddUser,
    buildChildUI wenv model -- or a sub section of the model
  ]
```

Sometimes this is all you need! One difference is that Composites check if their model changed before rebuilding the UI. In this version, any model change would trigger a UI rebuild, and the child section may not need to because the part of the model it cares about has not changed. You can recover that functionality by wrapping the result of `buildChildUI` with a `box` and using `mergeRequired`.

**Comment by prolic** [comment]
I tend to like the "don't need composite" approach. I will give it a try. Thank you very much for the help and advice you give.

**Comment by fjvallarino** [comment]
Note: I updated the example in _"You may not always need Composite"_, to pass _cevt_ to _ handleChildEvt_ instead of _evt_ (it was a copy/paste error).

**Comment by prolic** [comment]
Using this example

in Main-UI:

```haskell
Home.homeWidget (model ^. futrModel) SendPost
```

in Home:

```haskell
homeWidget model action =
  vstack [ -- some more code
  ]
```

I receive this error now:
```
    • Couldn't match type ‘AppModel’ with ‘FutrModel’
      Expected type: WidgetNode AppModel AppEvent
        Actual type: WidgetNode FutrModel AppEvent
```

Note that `FutrModel` in this case is a sub section of the main model that I want to use.

**Comment by prolic** [comment]
`Passing curried arguments to widgets` - I do the same for some MVar or TChan.

**Comment by prolic** [comment]
I tried to look into your other suggestion using a `compositeMergeModel`. Unfortunately there are not examples and I have no clue what to do with this option.

**Comment by prolic** [comment]
Sorry for spamming... I tried this now in the Main UI:

```
home :: FutrModel -> WidgetNode AppModel AppEvent
home model =
  vstack
    [ label "New Post"
    , spacer
    , vstack
        [ hstack
            [ textArea (futrModel . inputField)
              `nodeKey` "noteInput"
              `styleBasic` [ height 50 ]
            , filler
            , button "Post" SendPost
              `nodeEnabled` ((strip $ model ^. inputField) /= "")
            ]
        ]
    ]
```

which kind of works, but has some downsides. I cannot move this code out into it's on haskell module, as I would need to add a dependency to the Main Types, thus creating a circular dependency.

**Comment by prolic** [comment]
I also tried `Passing curried arguments to widgets` by passing `FutrModel` + it's own widget model into the child widget. This doesn't work for me, as the UI would be depending on two different models.

**Comment by prolic** [comment]
Sorry again, my problem was that I had put an `inputField` into the `FutrModel` which then was used to render some textarea object in the view and therefor my view was coupled with the wrong model. I moved it outside to the main, and now everythings works as suggested.
Using the `no composite needed approach`, rendering (besides the image rendering problem https://github.com/fjvallarino/monomer/issues/178) looks good so far.

When I understood you correctly, I need to add this for child widgets:
```
futrChanged wenv old new = old ^. futrModel /= new ^. futrModel
```
and then use with `mergeRequired futrChanged`, on a `box_ ` in which I render the child widget, correct?

Still don't understand what `compositeMergeModel` means or how it is used. But maybe that's not needed for my situation. Since most UI elements are pretty much many lines of vstacks, label and co, I want to factor those out into an extra module, instead of having a 2000 lines UI.hs, where I cannot find anything anymore. This works very well, since is my scenario all rendering related thing usually only depends on what's inside the websocket data.

Thanks again, you're a great help for me learning all those things. I hope to be able to write some custom UI widgets as well, still many things to learn. I love this project.

**Comment by fjvallarino** [comment]
Hi there! I'm not sure exactly where the issue with `inputField` was, but maybe what was missing was updating the lens you passed to the widget. If your Composite was using ChildModel, with a `userName` field:

```haskell
textField userName
```

And you moved ChildModel into MainModel (removing the Composite), you need to provide the full path to the field:

```haskell
textField (childModel . userName)
```
---

Regarding `mergeRequired`, you most likely need a single `box_` wrapping the section that used to be a Composite.

---
The `compositeMergeModel` config is useful when the model of your Composite is an _extension_ of some value in the parent model. For example, imagine the parent model has a list of `User`, and your Composite is a User editing widget. Let's say you want collapsible sections in that widget, but you need to store a few Bool flags to know what is expanded and what isn't. In that case, the model of the Composite would have User and as many Bool fields as needed. The problem is that the parent will give you a lens to a User, not to the model of the Composite. Since in `compositeMergeModel` you receive the complete parent model, you can use the given lens to extract the information you need and update your internal model.

A few things about Composites are still not in the tutorials. It's been months since I said I would push the `popup` and `colorPopup` widgets, which use this, but I have not had time to add a few missing configuration options and styling. I'll work on this since a lot can be improved. I also think a few things from this thread could be helpful there, mainly the idea that Composites are not the only way to split the UI into smaller chunks.

**Comment by prolic** [comment]
Thanks again.
