### ISSUE TITLE
Misunderstanding compositeMergeModel

### ISSUE THREAD

**Issue by klausweiss** [fjvallarino/monomer#196]
Hi. I am struggling with a custom `compositeMergeModel` handler. I am providing a custom handler and whenever it is called, old and new models are the same. Under what conditions do the old and new models differ?

Minimal example provided below. A simple app that appends a label widget to the rest whenever `C-n` is pressed.

<details>

```haskell
#!/usr/bin/env stack
{- stack
    script
    --resolver lts-19.16
    --extra-dep monomer-1.4.1.0
    --package monomer
    --package nanovg
    --package lens
    --package rio
    --package text
    --ghc-options=-threaded
-}

{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE NoImplicitPrelude #-}

module Main where

import Control.Lens (makeLenses, (<>~))
import Data.Text
import Monomer
import RIO

-- region composite

data CompositeEvent
    = LoadNextValue
    | AddValue Int

data ExampleCompositeModel = ExampleCompositeModel
    { _LoadedValues :: [Int]
    }

makeLenses 'ExampleCompositeModel

instance Show ExampleCompositeModel where
    show m = "\n" <> show (m ^. loadedValues)

instance Eq ExampleCompositeModel where
    m == n = m ^. loadedValues == n ^. loadedValues

buildCompositeUi wenv model = vstack $ label . tshow <$> (model ^. loadedValues)

handleCompositeEvent wenv node model evt =
    case evt of
        AddValue v -> [Model $ model & loadedValues <>~ [v]]
        LoadNextValue ->
            [ Task $ do
                return $ AddValue 1
            ]

mergeModel wenv parentModel oldModel newModel =
    traceShow (oldModel, newModel, oldModel == newModel) newModel

-- endregion

newtype AppModel = AppModel {_compositeModel :: ExampleCompositeModel}
    deriving (Eq)

data AppEvent
    = LoadMore
    deriving (Eq, Show)

makeLenses 'AppModel

buildUI wenv model = widgetTree
  where
    widgetTree =
        keystroke [("C-n", LoadMore)] $
            ( composite_
                "composite name"
                compositeModel
                buildCompositeUi
                handleCompositeEvent
                [compositeMergeModel mergeModel]
                `nodeKey` "composite"
            )

handleEvent wenv node model evt =
    case evt of
        LoadMore -> [Message "composite" LoadNextValue]

main = do
    startApp model handleEvent buildUI config
  where
    config =
        [ appFontDef "Regular" "Regular.ttf"
        , appTheme darkTheme
        ]
    compositeModel = ExampleCompositeModel []
    model = AppModel compositeModel
```
</details>

The custom merge handler is instructed to log a debug information - the old and new models and whether they're equal. The models are always the same. Shouldn't they only match once, on init? Example output:
<details>

```
(
[],
[],True)
(
[1],
[1],True)
(
[1,1],
[1,1],True)
(
[1,1,1],
[1,1,1],True)
(
[1,1,1,1],
[1,1,1,1],True)
```
</details>

**Comment by fjvallarino** [comment]
Hi @klausweiss!

This is something that lacks good documentation, and it needs to be part of the tutorials. Documentation improvements are next on the list of things to do after merging the `popup` PR and the `colorPopup` PR (which has not yet been submitted).

The use case for `compositeMergeModel` is when your composite needs to have a model different from the one the composite's user provides. It's not really useful for the top-level application since you provide it with the exact model you need.

For example, you could create a composite widget that provides the UI for editing the fields of a `User` type. The user of this composite only provides a lens to a `User` field in its model, but suppose your composite also shows collapsible sections in the UI. To support this you could use a few `Bool` fields, but the `User` type you received does not have them because they are not actual data for a User (they are just UI-related support fields). For this reason, you need to create your model type and add all the data you need.

```haskell
data UserUI = UserUI {
  _user :: User,
  _addressVisible :: Bool
  ... -- Any other field you need
}
```

### Interlude 1: WidgetData

Widgets in Monomer work with data in two different _formats_: lenses and values. The `WidgetData` type handles this through its data constructors `WidgetLens` and `WidgetValue` (you will see most widgets also have versions with a `V` suffix):

- The `WidgetLens` version simplifies getting and setting values since the lens is used directly on the user's model.
- The `WidgetValue` version requires more work but provides more flexibility. The user needs to provide the current value in `buildUI` (directly from the model or somehow deriving it) and handle an `onChange` event to update the model when the observed value changes (or even ignore the change request).

### Interlude 2: Composite state

Similar to other widgets (e.g., `textField` keeping the current cursor position), `composite` has its own internal state. One of the most important things it holds in its state is the model consumed by `buildUI` and `handleEvent`; `composite` also uses this model for checking if the UI needs to be rebuilt. All activity inside a `composite` is done using its internal model, completely ignoring the context of its parent.

The `compositeMergeModel` function allows for creating/updating the internal model while also incorporating information provided by the user/context. If the model used by the composite is exactly the same as the one provided by the user, there's no need to use this function.

### Back to the main topic

When you create a composite instance using a lens, you receive the getting/setting functionality for free. The problem is, in the scenario of user editing we're discussing, you don't have a lens to your `UserUI` model but a lens to `User`. Missing this lens means you don't have a place from where to get your complete mode, but you can use a `WidgetValue` with an instance of your type when you create your composite; this model will be kept in the composite's internal model and will not be visible by the user. Then, you can use `compositeMergeModel` to add the external information to it:

```haskell
userEdit :: (WidgetModel s, WidgetEvent e) => ALens' s User -> WidgetNode s e
userEdit field = userEditD_ (WidgetLens field)

userEditV  :: (WidgetModel s, WidgetEvent e) => User -> (User -> e) -> WidgetNode s e
userEditV value handler = newNode where
  newNode = userEditD_ (WidgetValue value)

userEditD_ :: (WidgetModel s, WidgetEvent e) => WidgetData s User -> WidgetNode s e
userEditD_ wdata = newNode where
  model = UserUI emptyUser False
  uiBuilder = ...
  eventHandler = ...
  {-|
  Update the internal model with the current user value.
  You might want to perform updates in your model-specific fields too. For example, if you detect the
  userId changed you could reset the addressVisible flag.
  When the internal model is not exposed, ignoring newModel makes sense because it's usually empty.
  -}
  mergeModel wenv parentModel oldModel newModel = oldModel
    & user .~ widgetDataGet parentModel wdata
  cfgs = []
  newNode = compositeD_ "userEdit" model uiBuilder eventHandler cfgs
```

You might have noticed that the widget's user never creates the `UserUI` type. This allows `userEdit` to be isolated from the parent model, providing only an interface through the `User` type (the only thing the user knows).

### Finally

In your sample code, you provide the `composite` instance with the `compositeModel` lens. Since composite takes care of reporting changes that happen within its context to the parent model, when the merge process happens the `old` and `new` values will already be the same (because the internal copy of the model is the same that was set in the parent).

In case your `LoadMore` modified `compositeModel . loadedValues` directly (triggering a merge), you should see a difference.

**Comment by klausweiss** [comment]
Wow, that was excellent and very comprehensive. Thank you!

In your example it should have been the following, no?
```haskell
  ...
  cfgs = [compositeMergeModel mergeModel]
  ...
```

**Comment by fjvallarino** [comment]
Yes, that's the case! I've updated the comment, to avoid confusion.

**Comment by fjvallarino** [comment]
In fact, there was another error. The content of `model` was meant to be wrapped by `WidgetValue`.

**Comment by klausweiss** [comment]
Perfect. Everything's clear for me, closing. Thanks again!
