### ISSUE TITLE
[Question] How to set a default font size globally

### ISSUE THREAD

**Issue by dimsuz** [fjvallarino/monomer#210]
Is there a way to change default font size globally for all widgets? Searched in styling tutorial and there was no mention of this, only examples of individual widgets' font size change.

P.S. Sorry for posting question here, I suspect it might not be a right place. Where should I post such one-off questions? Is there an irc channel / slack channel / discourse / whatever means for beginners like me to ask basic questions? :)

**Comment by dimsuz** [comment]
I've read a tutorial on styling more thoroughy and found this bit, I guess it gives an advice of an approach to follow:

> Considering the previous example, it would be nice to avoid duplicating the styling code all over the application. An easy way to avoid this is to create a function that returns the label styled as needed

**Comment by fjvallarino** [comment]
Hi @dimsuz!

Asking here is the best option, since previous questions can be useful to other people.

In general I prefer the approach of styling widgets using helper functions, but sometimes it's easier to change the default theme. [That section of the tutorial](https://github.com/fjvallarino/monomer/blob/main/docs/tutorials/08-themes.md) is not documented as well as it should, but the general idea is that you can provide a custom theme when the application starts. The [To-Do example](https://github.com/fjvallarino/monomer/blob/main/examples/todo/Main.hs#L262) does that.

To set an attribute in the theme, you can use the [mergeThemeStyle](https://hackage.haskell.org/package/monomer-1.5.0.0/docs/Monomer-Widgets-Util-Theme.html#v:mergeThemeStyle) helper function (in general you want to change an attribute's value and not reset the whole set of attributes, for which you can use `setThemeStyle`). You can see the available options [here](https://hackage.haskell.org/package/monomer-1.5.0.0/docs/Monomer-Core-ThemeTypes.html#t:ThemeState).

In your case you may want to do something similar to:
```haskell
main :: IO ()
main = do
  startApp MyModel handleEvent buildUI config
  where
    config = [
      ...
      appTheme customTheme,
      ...
  ]

customTheme = darkTheme
  & mergeThemeStyle L.labelStyle [textSize 10]
```

One thing that is important is that there is not a global text attribute that affects all widgets. Each widget has its own configuration, and you'll need to style each of them individually.

**Comment by dimsuz** [comment]
Great! Thank you for the detailed answer, I will try this!
