### ISSUE TITLE
Blurry fonts and icons

### ISSUE THREAD

**Issue by dimsuz** [fjvallarino/monomer#211]
I have a monitor which is generally produces blurriness when fonts are rendered, but running a monomer's "todo" example still feels very blurry. 

Here's the screenshot of how it looks for me.

![image](https://user-images.githubusercontent.com/42920/194963206-cb38d654-3cdc-42dd-8243-481a1ffacf97.png)

Notice that I taken it on top of a googlefonts' Roboto page opened in Firefox and its more crispy there.
"Tasks" header section label is especially blurry.
Also it seems that icon font is blurred too.

I am using `monomer-1.5.0.0` and in case this is somehow important, it's not strictly an example built in monomer's repo, but rather my own cabal-based project into which I have copied assets and `examples/todo` sources.

OS is ArchLinux, and here's the output when I run my executable:
```
Renderer: AMD Radeon RX 5500 XT (navi14, LLVM 14.0.6, DRM 3.47, 5.19.13-arch1-1)
Version: 4.6 (Core Profile) Mesa 22.1.7
```

**Comment by dimsuz** [comment]
Hmm after studying a screenshot a bit more, I'm not sure if this is a "bug": maybe Roboto in the browser page feels crispier because of the white background? But still my first reaction after launching the todo sample was "wow, it's hard to read" :)

**Comment by fjvallarino** [comment]
This looks more like an issue on the Window Manager/OpenGL driver side. If you look at the [examples](https://github.com/fjvallarino/monomer/blob/main/docs/examples/01-todo.md), which include a (heavily compressed) .gif, you'll see the text looks much crisper.

**Comment by dimsuz** [comment]
Yeah, I guess this has something to do with my system in the end. Maybe font rendering is somehow off (although `monomer` doesn't rely on system's font rendering I suppose, so it must be WM/OpenGL stuff as you've said).

I have also ran Styling example and some fonts look OK and some look blurry. Anyway if I'm the only one with this issue it's likely something on my side.

Sorry for the noise! :)

**Comment by CrystalSplitter** [comment]
I was wondering if you, @dimsuz, ever came up with a solution for this. I also have this same problem (kubuntu 2020).

I've noticed that it's quite a bit crisper with `appDisableAutoScale True` in the configs. So I'm wondering if monomer is doing some subpixel scaling because it's trying to predict my display scaling and getting that wrong?

**Comment by dimsuz** [comment]
Nope, I ended up thinking that this is somehow caused by the combination of graphics driver (amdgpu) + my monitor (Dell UltraSharp U2415) being not a good match. I have also found some threads on a bug in amdgpu which causes it to wrongly interpret this particular monitor's EDIDs which can also cause this blurriness. I even ended up with trying a workaround to substitute those EDIDs, but it didn't help much.

So in the end I'm still not sure what to think. On one hand, text in other apps (e.g. Firefox) kinda looks a bit blurry compared to my other devices, so it might be a gpu + monitor problem, but on the other hand text rendered in Monomer _seems_ to look more blurry than in other apps.

**Comment by fjvallarino** [comment]
@CrystalSplitter sorry, I missed this. I received the notification, but since the PR was closed, I forgot about it.

Yes, as you suspect, Monomer is trying to do some really bad display scaling detection. There is a related issue with a pending investigation [here](https://github.com/fjvallarino/monomer/issues/156). I'll keep that issue open and make sure to tag you once I get around to working on it.

Meanwhile, using `appDisableAutoScale True` combined with `appScaleFactor` could help to get the content to look as expected.

**Comment by khazaddum** [comment]
Hello, using `appDisableAutoScale True` and `appScaleFactor 2.0` fixed the blurriness on my app, but how can I change the default text size for the whole app? Everywhere the default text size is used, the text is very large.
