### ISSUE TITLE
when gif

### ISSUE THREAD

**Issue by srgtmshnk** [fjvallarino/monomer#232]
Hey @fjvallarino, can you share your roadmap for monomer? The most interesting part for me is gif and video support, but the entire roadmap would be interesting tho.

**Comment by fjvallarino** [comment]
Hi @srgtmshnk!

The roadmap, in broad terms, is the one found in the [README](https://github.com/fjvallarino/monomer#roadmap). My main objective is having a stable core that works in Linux, Windows, macOS and mobile (Android and iOS). I have not started work on the mobile part yet, but I'm getting into Nix since it seems the best option for cross-platform builds (mainly because of [Haskell.nix](https://input-output-hk.github.io/haskell.nix/)).

The missing detailed roadmap is a bit intentional; having one can somehow look like a commitment, and I don't want this project to feel like a job. I do, however, have things I'm planning to do in the medium-term:

- Improve text rendering in general (how it works and its performance).
- Add a Stack alternative that only updates (merges) the visible items.
- Fix some issues in Split widget and make it a bit more flexible.
- Improve documentation (this should be the top priority, really).
- Add support for emojis with color (unless it turns out to be too complicated).
- A bunch of little improvements to existing widgets.

In a way, all these items are related to having a decent experience in mobile. I'm also working on some improvements to the development workflow, that I hope to publish within a week or two. Making the library easy/nice to use is an important objective too.

Regarding the features you mention:

- I am planning on adding .gif support. It can be quite useful for spinners when data is being loaded, among other use cases. I don't have an ETA but it's something I want; I'm also planning to work on other improvements for the image widget.
- I don't have plans in the short/medium term for a video widget, although it would definitely be nice to have. One reason is I'm not sure the naive solution of treating each frame as an image would work well enough (I bet it doesn't). The other reason is it would demand a dependency on GStreamer or similar, and many users would not really use video; this leads me to think video would be a non-core widget.

**Comment by srgtmshnk** [comment]
Ok, thank you, i close the question
