### ISSUE TITLE
Horizontal and vertical scroll bars are inverted

### ISSUE THREAD

**Issue by edmeme** [fjvallarino/monomer#25]
In my setup (linux, X-org) when I scroll with two fingers, the scroll bar moves in the same direction as my fingers. In windows and mac/os it is often the other way around.

However, in monomer apps it seems like the Horizontal scroll bar moves in the opposite direction. I noticed this behavior in the OpenGL example app. [I checked the code and sure enough the sign is flipped between the stepX and stepY cases](https://github.com/fjvallarino/monomer/blob/332529a67a121e0ffc3db64977835d717bc48e52/src/Monomer/Widgets/Containers/Scroll.hs#L517).

Is the sign different to get the expected behavior in some platform? I can work on this issue

**Comment by edmeme** [comment]
butts are great

**Comment by fjvallarino** [comment]
The way it behaves currently is because of platform-related things (specifically, macOS). SDL2, or at least the Haskell bindings, reports the same device id for the trackpad and external mouse. The problem arises because the expected positive/negative direction is inverted on these devices. Since it was not possible to detect the event's origin, one had to be given priority (I chose mouse because it's what I use the most). If we find a way of detecting from which device an event comes, we can fix this issue. Otherwise, the scroll widget, or the Event module where the event is converted, may need platform-specific logic. 

The section where the SDL event is converted is [here](https://github.com/fjvallarino/monomer/blob/main/src/Monomer/Event/Core.hs#L98). You can import `Debug.Trace` to print detected device with (replace line 99):

```haskell
mouseWheelEvent epr mousePos (SDL.MouseWheelEvent eventData) = traceShow (SDL.mouseWheelEventWhich eventData) systemEvent where
```

What is the expected trackpad behavior on Linux/Windows? Does the direction match between using a trackpad and a mouse? I test Monomer on Linux using a VM and, unfortunately, the trackpad has already been processed by macOS.

**Comment by edmeme** [comment]
From what I read on the internet, this issue popped up when SDL started to account for system settings. It is a bit confusing to me that horizontal and vertical behavior differ. 

This is the behavior in linux; mouse buttons are assigned a number, scroll events are a button too. Scroll up is 4, scroll down is 5, scroll left is 6 and scroll right is 7 [1]. I verified that my touchpad produces the right events. Currently, in monomer apps, when I scroll up the scroll bar moves up, this is the default behavior in all apps. When I scroll right the scroll bar moves to the left, this is contradicting other apps. I get the same behavior with mouse and touchpad. My mouse only has scroll up/down, but if I remap the buttons 4 and 5 to the buttons 6 and 7 I get horizontal scrolling, and it behaves as expected in firefox but not in monomer apps.

IIRC, on Windows and Mac the expected behavior is the opposite; scrolling down should move the page down (and the scroll bar up).

I added 2 trace prints, as you suggested SDL.mouseWheelWich, but also SDL.mouseWheelDirection. I get the same device id "Mouse 0" for touchpad and mouse (so same as macOS) and SDL.ScrollNormal direction for both mouses, for horizontal and vertical scrolling. 
_Is the mouseWheelDirection SDL.ScrollNormal in macOS for touchpad and mouse?_

I suspect the issue is related to this https://discourse.libsdl.org/t/rfc-natural-scrolling-handling-on-mac-os-x/20424/10

[1] http://xahlee.info/linux/linux_x11_mouse_button_number.html

**Comment by fjvallarino** [comment]
Just to be sure: the issue only happens with horizontal scrolling? If that's the case, I can handle it conditionally for macOS (I can also test on Windows and adapt to it if there are differences). More specifically, for Linux I will remove the sign flipping for the horizontal case.

I'm thinking having configuration options for inverting horizontal/vertical scrolling may be a good idea.

**Comment by edmeme** [comment]
Yes, this only affects horizontal scrolling. 

Before doing what you suggest, you check the settings for your mouse in your mac. 
Apple introduced a feature in Yosemite they call "natural scrolling". Again, I don't own a mac,  but I can read on the internet that this flips tge direction of the vertical scroll. Also this setting is per-device: you can set it in your mouse and trackpad independently.

I suspect what we are seeing is a mix of the setting in your machine and perhaps an sdl2 bug that causes the reported direction to never be other than DirectionNormal.

This is a user complaining about a similar issue: https://discussions.apple.com/thread/6931607

**Comment by fjvallarino** [comment]
@edmeme I'm testing a few things.

Scrolling in macOS, as you mention, is reversed because of Natural Scrolling. For the sake of keeping an explanation in this issue for future readers: The idea of Natural Scrolling is the content should move in the same direction as if you dragged a sheet of paper. On the other hand, Standard Scrolling should move the content as if you dragged the scroll bar itself.

Before any testing, I flipped the horizontal scrolling logic to have `WheelNormal` not multiply by -1, with `WheelFlipped` doing it instead (same behavior as vertical scrolling).

- Testing this on Chrome works as expected. If Natural Scrolling is set, both Vertical and Horizontal follow the sheet of paper direction. If Natural Scrolling is disabled, they act as if dragging the scrollbars.
- Testing on Monomer, when Natural Scrolling is enabled Vertical Scrolling works correctly. Horizontal scrolling, on the other hand, acts as if dragging the scrollbar. This happens too when Natural Scrolling is not set: horizontal scrolling, in this case, follows the sheet of paper model (vertical still works as expected in this case). To summarize, horizontal scrolling is always the reverse of what it should be (that's the reason for the current -1 multiplication).

I will investigate a bit more to determine the source of the issue. I'll test on Windows too; I'm not sure if there is a user-friendly way of changing trackpad direction (I read a Registry entry is used).

Depending on these findings, I may release a version that handles macOS as a special case.

Once I have something, I'll push a branch and let you know.

**Comment by fjvallarino** [comment]
I tested both on macOS and Windows, and I pushed a new [branch](https://github.com/fjvallarino/monomer/compare/fix/scroll-wheel-handling?expand=1). 

Before this change, the scroll widget forced the direction based on the `WheelDirection` argument. This was a misunderstanding on my part, since the x/y offsets provided in the event already have that information included. With this change scrolling with the trackpad or mouse works as expected even after adjusting the scroll direction at the OS level, at least on Windows and macOS.

I wonder if maybe this fixes the issue for you too. If you get a chance to try it, please let me know!

**Comment by fjvallarino** [comment]
Just for reference, at least on Windows 10, the trackpad movement by default works as in macOS: sliding down moves the content up, sliding right moves the content left (the paper analogy mentioned previously). In both cases, this setting can be changed to follow the direction of the scrollbars.

**Comment by edmeme** [comment]
I tested your branch, and I fear it wont do for Linux.
`      stepX = -wheelRate * wx
      stepY = wheelRate * wy
`
There a minus on the X direction but not Y, so horizontal scroll behaves opposite to the rest of my apps, vertical scroll works as expected. 
Removing the minus makes both axis move in the same way, which also feels quite natural, minus sign -> inverted axis.
Notice I am not complaining about the preferred direction for my system as much as the fact that X and Y behave differently. 

Also, Its not a high priority for me, I'm just messing around.

**Comment by fjvallarino** [comment]
I added logic in a low-level layer to standardize the wheel movement (horizontal sign is negated for macOS/Windows, left as-is for Linux and others), so widgets consuming this event do not have to replicate this conversion. I tested on my Ubuntu VM, and it looks correct now (it still works fine on macOS and Windows).

I also added a couple of application-level configuration options (`appInvertWheelX`/`appInvertWheelY`) just in case the detection fails in some platforms.

Thanks for reporting this!

**Comment by edmeme** [comment]
I tested the branch, works beautifully! Thans for spending time on this :)

**Comment by fjvallarino** [comment]
Awesome! I'll release a new version to Hackage in the next few days (I also want to include an unrelated bug fix).

I'll close the issue for the time being. If you feel something is missing or want to add something else, please reopen it or create a new one.

Thanks for your help!
