### ISSUE TITLE
Build failing with SDL2 issue

### ISSUE THREAD

**Issue by peterjamesward** [fjvallarino/monomer#260]
I'm hoping to use the monomer package for a new Haskell GUI app. 
I struggle a lot with tools (cabal, stack, ghcup, brew, etc), so please make allowances. 
I'm on an M1 MacBook Air, and aware this adds complication. 
I have got further so far with a x86-64 install of ghcup, in as much as I can "stack build" and "stack exec" a baby console application.

I am so close now to monomer building, but there's this:

```
Configuring monomer-1.5.1.0...
monomer> build (lib + exe)
Preprocessing library for monomer-1.5.1.0..
Building library for monomer-1.5.1.0..
[  1 of 107] Compiling Monomer.Common.BasicTypes
[  2 of 107] Compiling Monomer.Common
[  3 of 107] Compiling Monomer.Common.Lens
<command line>: dlopen(/Users/peter/.stack/snapshots/x86_64-osx/a96a5ad76d190b44c809567fcba944cd8f4a81d09ae1cf67da7052c4060eac9e/9.2.5/lib/x86_64-osx-ghc-9.2.5/libHSsdl2-2.5.4.0-6ko4UgbuFKCKc2Pe5S0jk-ghc9.2.5.dylib, 0x0005): symbol not found in flat namespace '_SDL_AddEventWatch'

```
SDL2 appears to be 2.5.4.0 and the docs there say "This function is available since SDL 2.0.0.". Everything else was installed fresh this morning so should be latest.

Is this a flawed SDL2 build, a dependency error, ...?

**Comment by fjvallarino** [comment]
Hi @peterjamesward!

I'm also using an M1 MacBook, and since GHC 9.2 it works well without using Rosetta. I think the problem you have is that the system-level version of SDL2 is outdated (the 2.5.4.0 version is for the Haskell bindings). If you installed SDL2 with Homebrew, based on the [docs](https://docs.brew.sh/FAQ#how-do-i-update-my-local-packages) you can update it with:

```bash
brew update
brew upgrade sdl2
```

**Comment by fjvallarino** [comment]
Yes, all the tooling I'm using is for arm64. I guess the most important point is that you need to install Stack through ghcup, since the standard Stack installer does not support arm64.

I don't remember having to do something special to install arm64 libraries with Homebrew (I think it's the default).

**Comment by peterjamesward** [comment]
Happy days. Thank you so much for your response, it was timely and sorely needed.
<img width="618" alt="Screenshot 2023-02-21 at 11 17 03" src="https://user-images.githubusercontent.com/34382358/220330937-f8068a27-bcce-48df-970e-0eee36348a8e.png">
