### ISSUE TITLE
Composite merge bug when its model is WidgetValue

### ISSUE THREAD

**Issue by Deltaspace0** [fjvallarino/monomer#274]
When I need my composite to have more complex model than what the user is binding, I use `compositeD_ ... (WidgetValue newCompositeModel)` and `compositeMergeModel`.

The problem is that when merge happens, the composite model which is passed to `compositeMergeModel` is not the current composite model, but `newCompositeModel` which was used to create the composite.

I created minimal example to reproduce this behavior in dev-test-app [here](https://github.com/Deltaspace0/monomer/blob/bug/composite-merge/dev-test-app/CompositeSlider.hs).

I have composite which has a model with two fields (bound value and internal counter) and consists of a slider to change bound value and a button to increase internal counter. The user is passing only lens two the "Click count", so the slider changes this field.

When the composite is created, its model has both values equal to 0. When slider is used, then the request is sent to the parent to update the value. It causes a merge which sets composite model's internal counter to 0. I expected that it wouldn't be touched:

[composite-merge-bug.webm](https://github.com/fjvallarino/monomer/assets/26405676/91260bc2-49c2-4ed0-9b26-abab70a65fd3)

**Comment by Deltaspace0** [comment]
I learned that `userModel` is passed to `compositeMergeModel` config, but it is obtained through `widgetDataGet`, which in my case gets `WidgetValue` and returns initial composite model, not the current one when the merge happens.

https://github.com/fjvallarino/monomer/blob/a36492cb73ab4343c900f323ca5f5d710f7cffe8/src/Monomer/Widgets/Composite.hs#L584-L601

https://github.com/fjvallarino/monomer/blob/a36492cb73ab4343c900f323ca5f5d710f7cffe8/src/Monomer/Widgets/Composite.hs#L1035-L1040

I haven't managed to find where to get the current composite model from.

**Comment by fjvallarino** [comment]
@Deltaspace0 the issue is in how you define `mergeHandler`. It should be:

```haskell
    mergeHandler wenv parentModel oldModel newModel = oldModel
        & controlledValue .~ widgetDataGet parentModel wdata'
```

An example can be found in the [implementation](https://github.com/fjvallarino/monomer/blob/main/src/Monomer/Widgets/Singles/ColorPopup.hs#L194) of the `ColorPopup`, widget does something similar.

---

The rationale is that after you request the parent model to be updated in `EventReportNew`, a merge will happen, and your `mergeHandler` will be called. Once there, you want to keep most of your internal model and only update the parts that changed in the parent model you're interested in. That's why `oldModel` is used as the base since it's what was inside your widget before merge, while `newModel` will contain the model of the newly created version of the widget (which, in most cases, you will ignore unless you want your user to somehow reset your state).

**Comment by Deltaspace0** [comment]
@fjvallarino Hello, thank you for clarifying!

I had this issue with my app and tried using `oldModel` for merging too and it didn't work, so I created minimal example and forgot to check it with `oldModel` which actually works as needed. My actual problem was that I used my custom `enhancedSlider` composite inside a bigger composite and didn't provide proper `mergeRequired` config to it, which caused multiple slider values to switch back and forth, instead I focused only on the bigger composite and its `compositeMergeModel` config.

So the bug was in my app and not in the Monomer library.
