### ISSUE TITLE
Default Window Size?

### ISSUE THREAD

**Issue by liamzee** [fjvallarino/monomer#282]
I'm looking through the monomer source code right now (in truth, I'm looking for a way to simplify packaging assets with monomer without having to resort to cabal files or stack files), and one thing I notice is that the default window size is 800h * 600v, or a 4:3 ratio, considered good for productivity as it matches the human visual aspect ratio.

I know that monomer looking good is not necessarily an objective, but by using SDL, it seems to be a consequent effect of monomer.

To follow the aesthetic trend, might it make sense to default to a golden-ratio-like aspect ratio for defaults, such as WSVGA (1024h, 600v) or WVGA (800h, 480v) in an attempt to improve aesthetics?

**Comment by fjvallarino** [comment]
@liamzee the 800x600 size was chosen because it matches a very common aspect ratio used in computer screens.

It's a default value provided by the library, but you can change it to whatever is more appropriate to your application using the configuration option [appWindowState](https://hackage.haskell.org/package/monomer-1.5.1.0/docs/Monomer-Main-Types.html#v:appWindowState).

**Comment by liamzee** [comment]
I found the relevant configuration myself and ran a demo under a WSVGA window size. In reality, I'm not that conversant with UX design myself, and this is probably a spurious issue.
