### ISSUE TITLE
Best place to go for new-user-type questions?

### ISSUE THREAD

**Issue by chreekat** [fjvallarino/monomer#31]
Hiya,

I'm enjoying the library and making baby steps in writing my own gui app for the first time ever.

I think I'm making some basic user mistakes -- they're not bugs, I just don't know what I'm doing. Is there any sort of community space for library users to congregate and discuss such things?

**Comment by fjvallarino** [comment]
Hi @chreekat! I hadn't thought about that. I'm looking into it, and Gitter seems to be a good solution (I noticed Streamly uses it). 

Meanwhile, you can ask here! I want to create some sort of _"Recipes"_ section in the docs, explaining how to do common things (with associated code snippets), and this may be a good way to kickstart it.

**Comment by juhp** [comment]
You could also add Discussions tab here in the GitHub project - of course sometimes chat is easier. :-)

**Comment by fjvallarino** [comment]
@juhp thanks! I'll take a look into it.

I personally prefer using issues rather than chat (I have not yet looked into Discussions) since it gives me more time to think and come up with an answer that may be useful to future readers. Having said that, maybe having a chat channel is still a good idea if other people are interested in chiming in.

**Comment by chreekat** [comment]
> I tested on your original version, and both scenarios worked fine

Haha cool! That's certainly one way to solve the "new-user type questions": make sure they don't need to be asked in the first place. ;) Nice work!

**Comment by fjvallarino** [comment]
@chreekat I'll close the issue for the time being. If you feel something is missing, please re-open it or create a new one. Thanks!

**Comment by simmihugs** [comment]
### Very tiny scroll thumb

I hope its okay, that I ask here ...

I have a problem with `scroll` `scroll_` etc. 

In my application I create a `vstack` with a list of Widgets I create similar to the todo or books example. But my list, based on a xml file I parse is sometimes very large, like 2000 - 3000 items. And sometimes the xml file is shorter hence only 100 - 200 items.

in the case of the very large lists, the thum in the scroll bar becomes very tiny. Unfortunately, I could not figure out, how to cope with this in the expected way - I think I should do this somehow with the config for scroll_ ... right? I mean I was able to configure the look of the scrollbar, width, color radius etc. but the thumbnail is in relation to the number of items aka the length of the list.

my "solution" was to simply copy the source for `Monomer.Widgets.Containers.Scrolll` and manually make something like
```

scrollStatus
  :: ScrollCfg s e
  -> WidgetEnv s e
  -> WidgetNode s e
  -> ScrollState
  -> Point
  -> ScrollContext
scrollStatus config wenv node scrollState mousePos = ScrollContext{..} where
...
  hThumbRect = Rect {
    _rX = caLeft - hScrollRatio * dx,
    _rY = caTop + hScrollTop + (barW - thumbW) / 2,
    -- old   _rW = hScrollRatio * vpWidth,
    _rW = minimal $ hScrollRatio * vpWidth,
    _rH = thumbW
  }
  vThumbRect = Rect {
    _rX = caLeft + vScrollLeft + (barW - thumbW) / 2,
    _rY = caTop - vScrollRatio * dy,
    _rW = thumbW,
   -- old _rH = vScrollRatio * vpHeight
    _rH = minimal $ vScrollRatio * vpHeight
  }

minimal x
   | x < 50      = 50
   | otherwise = x
```

It fixes my problem ... but obviously I would like to understand how to do this in the expected way. Also this has the problem, that when you scroll down to the bottom, that you have to move the thumb over the end of the scrollbar end because it simply appends a larger rect to the actual thumb.

So yeah if you find the time to answer, that would be great and if I have to ask some where else let me know

**Comment by simmihugs** [comment]
I created `Config option for setting a minimum thumb size #61 `
