### ISSUE TITLE
Consider creating a separate package for examples

### ISSUE THREAD

**Issue by agentultra** [fjvallarino/monomer#42]
Depending on `monomer` also pulls in `websocket`, `wreq`, etc which then depends on the http stack which... a simple application that doesn't use any of those libraries doesn't need as a transitive dependency.

Could we move those dependencies for the examples to a package like `monomer-examples` or some such?

**Comment by agentultra** [comment]
Oh I see some of the widgets use it. Nevermind.

**Comment by fjvallarino** [comment]
Hi! I think your idea makes sense! The `websockets` dependency and others are only used by the examples, although `wreq` is indeed used by the `image` widget.

I'll keep it in mind for the next release.

Thanks!

**Comment by fjvallarino** [comment]
I removed several dependencies that were being lightly used (replaced them with custom code) and removed the dependency on `OpenGL` since it was redundant (`OpenGLRaw` was already included, and I updated some sections to remove the additional dependency). The `OpenGL` one is a big win in terms of build times.

For the moment, I will not move the examples to a new repository. They all serve a different purpose, and I test changes to the library using them to validate everything works well; having the examples in a separate package makes it harder for me to maintain/test.

Right now, the only dependencies used exclusively by the examples are `aeson`, `websockets`, and `wuss`. I will look into how I can avoid having them as dependencies for the library itself (they are not, but they are built because of the examples). One option is using build-time flags to exclude the examples, but it also has quirks. 

I will close the issue for now. Thanks!
