### ISSUE TITLE
accessing data files from monomer examples

### ISSUE THREAD

**Issue by smunix** [fjvallarino/monomer#44]
In order to make deployment a little more portable, can we use the following APIs provided by cabal? 
https://cabal.readthedocs.io/en/3.4/cabal-package.html#accessing-data-files-from-package-code

Without that, running the example binaries (/my/very/path/opengl for instance) fail to find the fonts and the vertex files.

> Renderer: NVIDIA GeForce GTX 770/PCIe/SSE2
> Version: 3.2.0 NVIDIA 470.86
> Failed to load font: Regular
> Could not find any valid fonts. Text size calculations will fail.

@fjvallarino let me know if you'd like me to push a PR

**Comment by fjvallarino** [comment]
@smunix if possible I'd like to avoid using that API, since (as far as I understand) it forces the user to list all the resource files in `data-files`, which can be annoying (although I think adding only the base directory is an option too). The idea is that the resource files are relative to where the application is executed, which works well on Windows, Linux, and macOS.

I wonder if this issue is related to how the examples are invoked using Nix. Is it possible to somehow set the working directory when running the examples using Nix?

**Comment by smunix** [comment]
Nix uses cabal to deploy files indeed; so it won't touch these files in asset unless specified in cabal. I'm afraid setting the CWD won't help after the package has been deployed. How do you deploy monomer apps on other Linux flavors or macOS? I could try  to replicate with Nix.

I guess the alternative is to copy these files manually wherever the binary located, for the following to work.
https://github.com/fjvallarino/monomer/blob/ad16b56f04a50edf332ade4a2076fcf965bf3c28/examples/tutorial/Tutorial01_Basics.hs#L66

**Comment by fjvallarino** [comment]
At least on macOS, you just need to have the `assets` folder inside the current working directory. For example, you can create a new directory `nested` inside the `monomer-starter` (or any other) project's folder, cd into `nested` and try running:

`../.stack-work/dist/x86_64-osx/Cabal-3.2.1.0/build/app/app`.

Since the program can't find the assets, it will show errors regarding missing fonts. If you then run:

`cp -r ../assets .`

and try again, it will work fine.

I tested on Windows a while ago and, beyond needing to copy the .dlls into a visible directory, it worked too.

**Comment by fjvallarino** [comment]
I don't think anything is pending here, so I'll close the issue for the time being. Please re-open if needed. Thanks!
