### ISSUE TITLE
How to create dialog window?

### ISSUE THREAD

**Issue by Abastro** [fjvallarino/monomer#57]
Hello, I wonder how I could create a dialog in separate window with monomer. How would I go with this?
Also I wonder if there is a way to have optional UI element which pops up only in certain circumstances without having to record the locql state in the monolithic state, for separation of concerns.
Thanks in advance!

**Comment by fjvallarino** [comment]
Hi @Abastro! 

Currently, there is no way of having multiple OS windows, but you can have dialogs in the style used in web pages or mobile applications, which show up on top of the rest of the content. You can see an example [here](https://github.com/fjvallarino/monomer/blob/main/docs/examples/02-books.md). When the dialog is open, the content below it does not receive events, effectively acting as a modal.

If you have UI elements whose state is independent of the rest of the application, you can:

- Create a [Composite](https://github.com/fjvallarino/monomer/blob/main/docs/tutorials/06-composite.md). A Composite works the same way as the top-level application, with both buildUI and handleEvent functions, but it can have its own state. The result is a widget that you can insert in the tree hierarchy as any other widget.
- Create a [custom widget](https://github.com/fjvallarino/monomer/blob/main/docs/tutorials/07-custom-widgets.md). Custom widgets are lower-level and usually require more work than using a Composite.

**Comment by Abastro** [comment]
Hi fjvallarino! Thank you for great answer. Will multiple OS windows be supported in the future versions?
I wonder how to give a custom local state for custom widgets. When I last checked the tutorial, it does not seem to talk much about the states..

**Comment by Dretch** [comment]
@Abastro 
> I wonder how to give a custom local state for custom widgets. When I last checked the tutorial, it does not seem to talk much about the states..

One way to have custom widget state is to use the [compositeD_](
https://hackage.haskell.org/package/monomer-1.2.0.0/docs/Monomer-Widgets-Composite.html#v:compositeD_) constructor passing `WidgetValue a` as the model argument. This allows the model (i.e. internal state) of the custom widget to be separate to the model of the parent widget.

**Comment by fjvallarino** [comment]
As @Dretch mentions, you can create a widget-local model by using `compositeD_` and `WidgetValue`. If you also need to retrieve information from the parent model, you can use [customModelBuilder](https://hackage.haskell.org/package/monomer-1.2.0.0/docs/Monomer-Widgets-Composite.html#v:customModelBuilder). This function is called on `init` and `merge`, and it provides as arguments the parent model and your model. If you passed a lens to a field in the parent model, you could use it to extract the information you need.

I'm using this in `ColorPopup`, a widget that I have not yet released since it's currently missing theming options and unit tests, where I receive a lens to a `Color` field in the parent model, but the model of `ColorPopup` has an additional flag:

```haskell
data ColorPopupModel = ColorPopupModel {
  _cpmPopupShowColor :: Bool,
  _cpmPopupColor :: Color
} deriving (Eq, Show)
```

Then, when creating the `WidgetNode`:

```haskell
colorPopupD_ :: (WidgetModel s, WidgetEvent e) => WidgetData s Color -> [ColorPopupCfg s e] -> WidgetNode s e
colorPopupD_ wdata configs = newNode where
  config = mconcat configs
  model = WidgetValue def
  uiBuilder = buildUI config
  eventHandler = handleEvent wdata config
  modelExtractor parentModel oldModel newModel = oldModel
    & popupColor .~ widgetDataGet parentModel wdata
  compCfg = [customModelBuilder modelExtractor]
  newNode = compositeD_ "colorPopup" model uiBuilder eventHandler compCfg
```

The `modelExtractor` function works similarly to the low-level `merge` of custom widgets, meaning if you want to keep the current state you have to consider what you have in `oldModel`. In this case, I'm interested in keeping the current `popupShowColor` value to avoid having the popup being closed when the user modifies the color.

I plan on releasing this widget shortly, as soon as I get a decent chunk of free time. It would also be a good addition as a reference in the documentation.

**Comment by Abastro** [comment]
Thank you all for kind answers, let me try. I cannot wait for ColorPopup as well!
