### ISSUE TITLE
Feature Request: some way to change spacing on LabeledCheckbox

### ISSUE THREAD

**Issue by Dretch** [fjvallarino/monomer#59]
Hello,

I have a checkbox in my app that looks like this:
![Screenshot at 2022-01-09 21-35-39](https://user-images.githubusercontent.com/1428731/148701921-6fac514b-6413-419b-9482-8908dcc342a6.png)

However, I would like it to look like this (with less space between the icon and the label, to match the spacing in rest of the UI):
![Screenshot at 2022-01-09 21-34-46](https://user-images.githubusercontent.com/1428731/148701947-97755d9c-ce89-441e-a676-9d3ff37253ed.png)

What do you think about adding adding a configuration option to `LabeledCheckboxCfg` to allow changing the spacing? It might be called `childSpacing` and could potentially apply to other widgets too (possibly containers like {v,h}stack?).

If you decide this makes sense, I can look into sending a PR.

Thanks!

**Comment by fjvallarino** [comment]
That would be a great feature!

I think you have two options:

- Add a configuration option to `LabeledCheckbox` and modify `LabeledItem` to set the `spacer` to the provided width.

Or:

- Add a configuration option to `hstack`/`vstack` to handle spacing between components. In this case, the `spacer` in `LabeledItem` could be removed.

The second option is nice since it would be useful in many other places, but it's also quite a bit more work.

Both options are good for me. Just in case, there is a `watch-tests.sh` script that starts `ghcid` and is useful when writing unit tests.

**Comment by Dretch** [comment]
Thanks @fjvallarino, I'll have a look into this (the second option, if possible).

**Comment by fjvallarino** [comment]
I think this issue is now complete after merging your PR. If you feel something is missing, please re-open or create a new issue. Thanks!
