### ISSUE TITLE
Unbuildable

### ISSUE THREAD

**Issue by hasufell** [fjvallarino/monomer#7]
This package was uploaded to hackage but is unbuildable, due to:

https://github.com/fjvallarino/monomer/blob/523355c389621330d3f026384b9673548a3f5f8d/stack.yaml#L46-L49

```
$ cabal install monomer                                                                                                                      2516ms  Sat 09:28
cabal: Could not resolve dependencies:
[__0] trying: monomer-1.0.0.1 (user goal)
[__1] next goal: nanovg (dependency of monomer)
[__1] rejecting: nanovg-0.6.0.0 (conflict: monomer => nanovg>=0.8 && <1.0)
[__1] skipping: nanovg-0.5.2.0, nanovg-0.5.1.0, nanovg-0.5.0.0,
nanovg-0.4.0.0, nanovg-0.3.0.0, nanovg-0.2.0.0, nanovg-0.1.0.2,
nanovg-0.1.0.1, nanovg-0.1.0.0 (has the same characteristics that caused the
previous version to fail: excluded by constraint '>=0.8 && <1.0' from
'monomer')
[__1] fail (backjumping, conflict set: monomer, nanovg)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: monomer, nanovg
```

**Comment by fjvallarino** [comment]
Hi @hasufell! Yesterday I submitted a PR to see if it is possible to have `libglew-dev` added to the list of available libraries on Hackage. That missing library is causing nanovg's 0.7.0.0 build to fail and is the reason why I'm waiting to push 0.8.0.0 to Hackage (which, in turn, causes the Monomer build failure).  As soon as that library is available, or if the PR is rejected, I will push 0.8.0.0 to Hackage and all should work fine. 

I'm not really familiar with using Cabal freeze files (I mostly rely on Stack), and I worry that having the freeze file in the repository could cause issues in the future (mainly because I will forget to update it). Is it standard practice to commit freeze files? I have not seen them in the dependencies I use (for example, sdl2), although I have seen references to using Stackage indexes in Cabal builds.

**Comment by hasufell** [comment]
> I'm not really familiar with using Cabal freeze files

delete it then, it shouldn't be needed

**Comment by fjvallarino** [comment]
@hasufell nanovg-0.8.0.0 now builds fine on Hackage (the libglew-dev PR was recently accepted). I also deployed monomer-1.0.0.2, which references that version of nanovg instead of the old commit hash.

**Comment by fjvallarino** [comment]
@hasufell sorry for the delay; PR https://github.com/fjvallarino/monomer/pull/8 is merged now.

I think the issue can be closed now. Don't hesitate to re-open it, or create a new one, if you feel something Is missing.

Thanks!
