### ISSUE TITLE
How to access hidden State of widgets

### ISSUE THREAD

**Issue by simmihugs** [fjvallarino/monomer#83]
Hi,

I was thinking about creating a container widget, which takes a textarea widget as input and adds line numbers.
For that I was thinking to have a look at `box` for the container and `label` as a way to display the linenumbers - but feel free to recommend other widgets I should rather have a look at.

What I was wondering is - how can the container access the internal state of textarea - specifically I want to make it possible(by cfg) for the
linenumber widget to change the color and/or font of the current line - current line refering to the y positon of the cursor in the textarea

**Comment by fjvallarino** [comment]
Hi! There is no easy way of accessing the internal state since it's mainly meant to be used by the widget itself. I'm not recommending doing this but, in general, you could:

- Since you are in a container, you can use `node ^. L.children` to access your children (probably a single element).
- The items in `L.children` are of type `WidgetNode`; you can use `node ^. L.widget` to have access to the `Widget` instance of a given node.
- Once you have a `Widget` instance, you can call `widgetGetState` to get the state (it returns `Maybe s`). You will need to use `Data.Typeable.cast` to cast to the correct type.

Unfortunately, in this case, `textArea` does not export its state type, so you will not be able to cast to it. 

--- 

_The following section focuses only on displaying line numbers but can be adapted to the other scenarios._

In my opinion, creating a custom `textArea` widget is a more flexible option. You would need to:

- Add a new configuration option to enable showing line numbers.
- Modify `getSizeReq` to account for the extra space of the margin containing the numbers.
- Modify `render` to display them.

Rendering, in this case, is a bit tricky. Each node has a `node ^. L.viewport` property that indicates the assigned space for rendering. This viewport is valid even inside a `scroll`, although its content will be clipped according to scroll position. The consequence is if you start rendering the line numbers from `node ^. L.viewport`'s top-left, they will not be visible anymore whenever the user scrolls to the right. To handle this, you can take `wenv ^. L.viewport` into account since it always contains the non-clipped available viewport (you can use `intersectRects` to get the node's available space). Once you have the correct viewport, you can draw line numbers that are always visible. The text lines need to be offset to the right by the width of the new margin.

**Comment by fjvallarino** [comment]
I mentioned the idea of creating a custom widget since line-based font switching goes beyond the simplicity of what `textArea` does (it's more like a Notepad than a Rich Text Editor), but having line numbers would be a valuable feature for many users! If you want to modify `textArea`, I'll be happy to review the PR/provide guidance.

Optional line numbers on `textArea` is a feature I have pending to add but, since I can't commit to a timeline, I don't want to keep you waiting until I get around to doing it. Optionally highlighting the current line (background) would be nice to have too.

**Comment by simmihugs** [comment]
Yes to the highlighting of the current line too

I dont know how soon I will be able to do so
but I will definitely try it and if it is not completely garbage
of course I will give the change back to you so you can have a look

**Comment by simmihugs** [comment]
So this is my first try with it

![grafik](https://user-images.githubusercontent.com/51531595/155132902-0b3d71c8-0365-497e-a375-14f51a573a56.png)

As you recommended I
-  Add a new configuration option to enable showing line numbers.
-  Modify getSizeReq to account for the extra space of the margin containing the numbers.
-  Modify render to display them.

But I'm a bit confused what you said here, qoute:
_Rendering, in this case, is a bit tricky. Each node has a node ^. L.viewport property that indicates the assigned space for rendering. This viewport is valid even inside a scroll, although its content will be clipped according to scroll position. The consequence is if you start rendering the line numbers from node ^. L.viewport's top-left, they will not be visible anymore whenever the user scrolls to the right. To handle this, you can take wenv ^. L.viewport into account since it always contains the non-clipped available viewport (you can use intersectRects to get the node's available space). Once you have the correct viewport, you can draw line numbers that are always visible. The text lines need to be offset to the right by the width of the new margin._

I dont understand what you mean with node, viewport ... yeah ... can you elborate on that?
This is what I did to display the line numbers (obviously it's just a heckie attempt)

```
  render wenv node renderer = do
    drawInTranslation renderer (offset 0) $ do
      forM_ (f textLines) (drawTextLine renderer $ g style)

    drawInTranslation renderer (offset $ widthLineNumbers) $ do
      when selRequired $
        forM_ selRects $ \rect ->
          when (rect ^. L.w > 0) $
            drawRect renderer rect (Just selColor) Nothing

      forM_ textLines (drawTextLine renderer $ g style)

      when caretRequired $
        drawRect renderer caretRect (Just caretColor) Nothing
    where
      f = Seq.mapWithIndex (\x t -> t
                             & L.text .~ (T.pack $ show x)
                             & L.font .~ (Font "MonoItalic")
                           )
      g styleS = styleS
                 & L.bgColor .~ (Just $ rgbHex "#e69947")
                 & L.fgColor .~ (Just $ rgbHex "#1a15a5")
```

The next thing I will have a more closer look is, to use different font, background color etc. for line numbers ...

**Comment by fjvallarino** [comment]
Sorry, I missed this because the issue was closed. 

Each `WidgetNode` (an instance of a `Widget`, plus information about location, visibility, etc.) has an associated `viewport` that represents the area where it can render its content. You can access this `Rect` in all widget-related functions with `node ^. L.info . L.viewport`. When you add a widget to a regular container (`hstack`, `vgrid`, `box`), the node's viewport will be visible at all times (as long as it fits inside the screen). This may not be true if the widget is embedded inside a `scroll` instance since the user may drag the handles to show different parts of the underlying widget (this is the case of `textArea`). When a widget is embedded in a `scroll` (or `hscroll`/`vscroll`):

- The widget will be assigned all the space it requests in `getSizeReq` (with axis restrictions if using the h/v versions)/
- The assigned area, as in any other case, will be in `node ^. L.info . L.viewport`. The widget can draw freely in this space, with the `scroll` widget taking care of clipping.
- In case the widget prefers to do some optimizations (e.g., only draw the visible text lines), or has a particular need (the line numbers case), the currently visible viewport (the part visible inside the scroll) is available in `wenv ^. L.viewport`.

Going back to the original discussion, if you draw the numbers using `node ^. L.info . L.viewport` they will not be visible when the user scrolls to the right because they will be drawn at the very left of the widget's assigned space. To avoid this, you can use `wenv ^. L.viewport`. The general idea would be to:

- Request extra space for the line numbers (you are already doing this).
- Render the text lines with an offset equal to the width the line numbers will take.
- Taking into account the width the line numbers use, apply a `drawInScissor` before drawing the text lines (it would take `wenv ^. L.viewport` into account).
- Draw the line numbers in the space before the text lines (also taking `wenv ^. L.viewport` into account).

The code might be something like:
```haskell
-- Restrict drawing to keep the line number section free
let textLinesRect = wenv ^. L.viewport & L.x +~ your_line_number_width
-- Add x offset to the text lines, otherwise the beginning of each line would not be visible
let textLinesOffset = Point your_line_number_width 0
-- Restrict the line numbers to the width you assigned
let lineNumbersRect = wenv ^. L.viewport & L.w .~ your_line_number_width

drawInScissor renderer True textLinesRect $
   drawInTranslation renderer textLinesOffset $
      -- Old text lines drawing code
      ...

drawInScissor renderer True lineNumbersRect $
   -- New line number drawing code
   ...

```

**Comment by simmihugs** [comment]
Thanks for your response - My bad I did not reopen the issue

I will have a look at it and try to incorpriate it into my own changes and let you know if I have more questions

**Comment by simmihugs** [comment]
Okay, I took your advise and played around with it a little

![fragment](https://user-images.githubusercontent.com/51531595/155823889-59020603-5a45-4114-9661-d40f21812c12.gif)

Hurray! But now there are a bunch of things which I have to look at
1. scrolling keeps the linenumbers visible but they move slightly back and forth to the left, right
2. The cursor is not aware of the shift to the right, so when selecting something, one needs to move cursor more to the left
    ![fragment2](https://user-images.githubusercontent.com/51531595/155823984-bfe73f99-cce8-42ca-be2c-e5bd0e3e56dc.gif)
3. Why are the linenumbers not using the different colors? 
4. Rightnow everything uses hard coded values for linenumber width and where to draw the linenumbers etc

```haskell
  render wenv node renderer = do
    -- Restrict drawing to keep the line number section free
    let textLinesRect = wenv ^. L.viewport & L.x +~ lineNumberWidth
    -- Add x offset to the text lines, otherwise the beginning of each line would not be visible
    let textLinesOffset = Point lineNumberWidth 0
    -- Restrict the line numbers to the width you assigned
    let lineNumbersRect = wenv ^. L.viewport & L.w .~ lineNumberWidth

    drawInScissor renderer True textLinesRect $
      drawInTranslation renderer offset $ do
      when selRequired $
        forM_ selRects $ \rect ->
          when (rect ^. L.w > 0) $
            drawRect renderer rect (Just selColor) Nothing
  
      forM_ textLines (drawTextLine renderer style)

      when caretRequired $
        drawRect renderer caretRect (Just caretColor) Nothing

    drawInScissor renderer True lineNumbersRect $ do
      mapM_ f [1..length textLines]
      
    where        

      f =  drawTextLine renderer otherStyle . (\x -> textLine (T.pack $ show x) (fromIntegral $ 7+x*20))
      otherStyle = style { _sstBgColor = Just $ rgbHex "#576bba", _sstFgColor = Just $ rgbHex "#ff2200", _sstSndColor = Just $ rgbHex "#3d804e"}
      textLine t y = def
                 & L.text .~ t
                 & L.rect .~ Rect (wenv ^. L.viewport . L.x + 5) y 20 20
                 & L.fontSize .~ FontSize 15

      style = currentStyle wenv node
      contentArea = getContentArea node style
      ts = _weTimestamp wenv
      offset = Point (contentArea ^. L.x + lineNumberWidth) (contentArea ^. L.y)
```

**Comment by fjvallarino** [comment]
1. The reason why the line numbers jump back and forth is that the padding is affecting the viewport size; I missed subtracting it when I typed the example code. One way you can check this type of thing is by drawing a red rectangle (or any other color) for testing. Is not a sophisticated means of debugging, but it's quite helpful. In this case, you can change the example code pasted below to `wvp = wenv ^. L.viewport`, uncomment the `drawRect` line and see more clearly what was happening.
2. You need to check `findClosestGlyphPos`, since it also needs to consider the new space at the left added by the line numbers. I suggest you pass it an extra `TextAreaCfg` argument from where you can retrieve the line number width (and also know if it's enabled).
3. Because you are only rendering text, and text color is a property inside `style ^. L.text . L.fontColor`. If you want to render a background (`bgColor`) you need to manually draw a rectangle (or use `drawStyledAction`, that receives renderer, rect, style, and action that can be your line number rendering one). 

In case more questions arise, could you paste the complete function or push it to a repo? It will make it easier for me to validate.

```haskell

  render wenv node renderer = do
    drawInScissor renderer True textLinesRect $
      drawInTranslation renderer offset $ do
      when selRequired $
        forM_ selRects $ \rect ->
          when (rect ^. L.w > 0) $
            drawRect renderer rect (Just selColor) Nothing
  
      forM_ textLines (drawTextLine renderer style)

      when caretRequired $
        drawRect renderer caretRect (Just caretColor) Nothing

    --drawRect renderer lineNumbersRect (Just (rgbHex "#ff2200")) Nothing

    drawInScissor renderer True lineNumbersRect $ do
      mapM_ renderLineNumber [1..length textLines]
      
    where        
      style = currentStyle wenv node
      contentArea = getContentArea node style
      ts = _weTimestamp wenv
      lineNumberWidth = 50
      offset = Point (contentArea ^. L.x + lineNumberWidth) (contentArea ^. L.y)
      focused = isNodeFocused wenv node

      caretTs = ts - _tasFocusStart state
      caretRequired = focused && even (caretTs `div` caretMs)
      caretColor = styleFontColor style
      caretRect = getCaretRect config state False

      selRequired = isJust (_tasSelStart state)
      selColor = styleHlColor style
      selRects = getSelectionRects state contentArea

      -- Remove padding and border from visible viewport (same as getContentArea but passing a Rect instead of a Node)
      wvp = fromMaybe (wenv ^. L.viewport) (removeOuterBounds style (wenv ^. L.viewport))
      -- Restrict drawing to keep the line number section free
      textLinesRect = wvp & L.x +~ lineNumberWidth
      -- Add x offset to the text lines, otherwise the beginning of each line would not be visible
      textLinesOffset = Point lineNumberWidth 0
      -- Restrict the line numbers to the width you assigned
      lineNumbersRect = wvp & L.w .~ lineNumberWidth
      renderLineNumber = drawTextLine renderer otherStyle . (\x -> textLine (T.pack $ show x) (fromIntegral $ 17+x*20))
      --otherStyle = style { _sstBgColor = Just $ rgbHex "#576bba", _sstFgColor = Just $ rgbHex "#ff2200", _sstSndColor = Just $ rgbHex "#3d804e"}
      otherStyle = style
        & L.text . non def . L.fontColor ?~ rgbHex "#000000"
      textLine t y = def
        & L.text .~ t
        & L.rect .~ Rect (wvp ^. L.x + 5) y 20 20
        & L.fontSize .~ FontSize 15
```

**Comment by simmihugs** [comment]
Hi @fjvallarino,

thanks for the reply and yes I want to push it to the repo - I not that familiar with github yet. I did made a fork of `monomer` and made my changes; next I push it to my own branch and then make a pull request ... right?

I will make this as soon I had time to look at your reply in more detail - an either be able to fix my issues --> than I would like your opinion etc.
or I run into another wall ;) and more questions arise

**Comment by fjvallarino** [comment]
No problem if you want to work on a separate repository. If you forked the project and pushed a branch to your repo, I'm fine with reviewing the code there. Having the complete code in a single place will make it easier for me to review because I will know the values of the constants you use, etc.

**Comment by simmihugs** [comment]
Okay I thought this is the way you are supposed to do it and I did not know I could push to your monomer prepository directly(?).

As I already made a fork I probably go ahead this way. 
But I do need to send a pull request inorder for you seeing I made a change, right?

**Comment by fjvallarino** [comment]
You can send a pull request once you are happy with the implementation; there is no need to hurry. If you share a link to your repository indicating the branch you are using, I can check it as long as the repository is public.

**Comment by simmihugs** [comment]
Okay allright

this is the link https://github.com/simmihugs/monomer/tree/add-linenumber-to-textarea

once I'm are happy with it I will make a request

**Comment by fjvallarino** [comment]
I don't think anything is pending from my side, so I'll close this issue for the time being. Please re-open if needed. Thanks!

**Comment by simmihugs** [comment]
I finally found some time to revisit this.

![grafik](https://user-images.githubusercontent.com/51531595/159380793-33650ff7-269b-4595-8517-ba447de247c3.png)

I was able to add the following functionallities:
- Syntaxhighlighting
- Linenumbers && highlighted current linenumber
- Highlight current Line
- Selection works as expected
all handled by config options for textArea.

Two things though:
- It could not fix the jumping of the linenumbers - I tried to remove the padding as you suggested, but it still jumps back and forth
- My syntaxhighlighting method looks okay, but if you switch it on an off ... there is movement in the text, so I make mistakes in my alignment of the text

Maybe you have a tip on how to deal with these two things

This is the code for the renderer in TextAreaWidget (I'm using a [open repo](https://github.com/simmihugs/monomer-textArea/blob/main/README.md) for this with only the nesseary code - whole monomer took quite long to build everytime):
```haskell
  render wenv node renderer = do
    let font = fromMaybe def (style ^? L.text . _Just  . L.font . _Just)
    let fontSize = fromMaybe def (style ^? L.text . _Just . L.fontSize . _Just)

    -- Highlight current line
    let textLinesRect   = wenv ^. L.viewport & L.x +~ lineNumberWidth
    drawInScissor renderer True textLinesRect $
      drawInTranslation renderer offset $ do
      case _tacCurrentLineColor config of
        Nothing -> return ()
        color   -> do
          let indexCurrentLine   = snd $ _tasCursorPos state
          let currentLine        = Seq.index textLines indexCurrentLine
          let (Rect tx ty tw th) = _tlRect currentLine
          let maxLineLength      = Seq.foldlWithIndex (\startValue _ textLine -> do
                                                          let tmpLength = _rW (_tlRect textLine)
                                                          if tmpLength >= startValue
                                                            then tmpLength
                                                            else startValue) 0 textLines
          drawRect renderer (Rect (-10) (ty-5) (10+maxLineLength) (th+10)) color Nothing

      when selRequired $
        forM_ selRects $ \rect ->
          when (rect ^. L.w > 0) $
            drawRect renderer rect (Just selColor) Nothing
        

      -- Syntax Highlighting
      case _tacSyntax config of
        -- Apply syntax highlighting
        Just (Just syntaxTree,syntaxMap) -> do
          let textLines' = Seq.mapWithIndex (\index value -> value & L.fontSize .~ fontSize) textLines
          MyDrawing.drawTextSyntaxed renderer style syntaxTree syntaxMap textLines'
        -- No syntax highlighting
        _          -> do
          let textLines' = Seq.mapWithIndex (\index value -> value & L.fontSize .~ fontSize) textLines
          forM_ textLines' (drawTextLine renderer style)

      when caretRequired $
        drawRect renderer caretRect (Just caretColor) Nothing


    -- draw LineNumbers
    let lineNumbersRect = wenv ^. L.viewport & L.w .~ lineNumberWidth
    let otherStyle color = style & L.text . non def . L.fontColor ?~ color
    let rH' = if textLines ==  Seq.empty
              then 5
              else do
          let line   = Seq.index textLines 0
          let space  = unFontSpace $ _tlFontSpaceV line
          let height = _rH $ _tlRect line
          height + space
    let textLine t y = do
          let wvp = fromMaybe (wenv ^. L.viewport) (removeOuterBounds style (wenv ^. L.viewport))
          let rect' = wvp & L.x +~ 5 & L.y .~ y & L.w .~ 20 & L.h .~ 20
          --let rect' = Rect (wenv ^. L.viewport ^. L.x + 5) y 20 20
          def
            & L.text .~ t
            & L.rect .~ rect'
            & L.fontSize .~ fontSize
            & L.font .~ font
    let renderLineNumber = renderIndexLine . createIndexLine
          where
            lineStyle index =
              otherStyle $ if index==succ (snd $ _tasCursorPos state)
                           then rgbHex "#ff2200"
                           else rgbHex "#000000"
            renderIndexLine (index,line) = drawTextLine renderer (lineStyle index) line
            createIndexLine x            = (x,textLine (T.pack $ show x) (35 + fromIntegral x * rH'))
    when (fromMaybe False (_tacShowLineNumbers config)) $ do
        drawRect renderer lineNumbersRect (Just (fromMaybe (rgbHex "#ff2200") (style ^. L.sndColor))) Nothing
        drawInScissor renderer True lineNumbersRect $ do
          mapM_ renderLineNumber [1..length textLines]
    where
      style = currentStyle wenv node
      contentArea = getContentArea node style
      ts = _weTimestamp wenv
      offset = Point (lineNumberWidth + contentArea ^. L.x) (contentArea ^. L.y)
      focused = isNodeFocused wenv node

      caretTs = ts - _tasFocusStart state
      caretRequired = focused && even (caretTs `div` caretMs)
      caretColor = styleFontColor style
      caretRect = getCaretRect config state False

      selRequired = isJust (_tasSelStart state)
      selColor = styleHlColor style
      selRects = getSelectionRects state contentArea

```
