### ISSUE TITLE
Feature request: text widget that is selectable but not editable

### ISSUE THREAD

**Issue by Dretch** [fjvallarino/monomer#87]
Hello,

It would be useful for me to have a widget that displays text that can be selected (and copied), but cannot be edited.

Currently I don't think this exists: textfield/areas can be disabled to stop editing, but then you can't select the text either. Labels don't currently allow selecting.

Could textfield/area perhaps have a `readonly` option? I can probably send a PR.

**Comment by fjvallarino** [comment]
It would really be nice to be able to select text on non-editable content. As you suggest, the easiest route is adding the `readOnly` configuration option to `textField` and `textArea` since these widgets already implement the selection functionality. Adding text selection to `label` would be a bit painful.

The `textField` widget uses `InputField` underneath, since it provides all the editing functionalities also used by `numericField`, `dateField` and `timeField`. All of these widgets pass configuration options down to `InputField`. It would also be great to have the readonly option on those widgets too!

**Comment by fjvallarino** [comment]
My only concern is that `editable` is a common name to have in a record, and it can cause issues when generating lenses. Of course, the same can happen with `readOnly`, although somehow I feel it's a bit less common. I don't have a strong preference.

**Comment by Dretch** [comment]
Fair enough @fjvallarino -- I don't have a preference so I will go with `readOnly`.

**Comment by klausweiss** [comment]
Hey, I also have a usecase for such a widget. Would implementing it as a `readOnly` config option to textfield/textarea allow selecting text from multiple such widgets at once? Say I have multiple labels next to each other and want to select text from all of them, like I can do in a web browser now:

![image](https://user-images.githubusercontent.com/11031002/156223936-ea16441d-588b-4038-bd5f-4fce1907370b.png)

**Comment by Dretch** [comment]
@klausweiss the most straightforward way of implementing readOnly will not allow selecting across multiple widgets. I suspect it would be quite a difficult/large change to get that to work: there would need to be some sort of global selection context that peeks inside all the widgets, or something… I’m not attempting this right now anyway!

**Comment by fjvallarino** [comment]
@klausweiss selecting text from multiple widgets is not possible. Monomer behaves similarly to desktop/mobile libraries such as GTK or Flutter, instead of following a document object model where there is an implicit and selectable document (there is a similar [discussion](https://github.com/flutter/flutter/issues/79629) in Flutter's repository).

I'm not sure what your requirements are, but if you need to make information available on the clipboard from the main application handler (or from a `Composite`), you can use:
```haskell
handleEvent wenv node model evt = case evt of
   CopyEvent -> [ Request (SetClipboard (ClipboardText "Now in clipboard")) ]
   ...
```
If you implement a custom Widget, you can make the same `WidgetRequest` when handling events (and other functions such as `handleMessage`).

```haskell
handleEvent wenv node target evt = case evt of
    KeyAction mod code KeyPressed
      | isKeyboardCopy wenv evt -> Just (resultReqs node [ SetClipboard (ClipboardText "In custom widgets too") ])
   _ -> Nothing
```

**Comment by klausweiss** [comment]
I see, that's kind of what I expected. I don't want to hijack this thread. If that's ever a hard requirement for me, I'll try to come up with something or I'll open a discussion. Good to know that won't be possible for now.

**Comment by fjvallarino** [comment]
@Dretch I'm closing this issue since the PR was merged. Feel free to re-open if something is missing. Thanks!
