### ISSUE TITLE
Error when running example: glMakeCurrent

### ISSUE THREAD

**Issue by tomsmeding** [fjvallarino/monomer#9]
Trying to run [the first tutorial example program](https://github.com/fjvallarino/monomer/blob/523355c389621330d3f026384b9673548a3f5f8d/examples/tutorial/Tutorial01_Basics.hs) by creating a new cabal project, adding nanovg-hs at https://github.com/cocreature/nanovg-hs/commit/ba8733f58da63e0934b5d2853ed84b71e872e6f1 and monomer at https://github.com/fjvallarino/monomer/commit/523355c389621330d3f026384b9673548a3f5f8d as in-tree dependencies. I also set the `stb_truetype` flag to true on nanovg because monomer's stack.yaml does that.

Everything compiles (with some unused-import warnings in nanovg-hs), but running the resulting executable produces the following output:

```
Renderer: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
Version: 3.2.0 NVIDIA 470.57.02
test: SDLCallFailed {sdlExceptionCaller = "SDL.Video.OpenGL.glMakeCurrent", sdlFunction = "SDL_GL_MakeCurrent", sdlExceptionError = "Unable to make GL context current"}
```

(`test` is the name of the executable)

A window is created but nothing is ever drawn in it (only the window border gets drawn on my system). When I close the window, the application does print `About to destroyWindow`; I believe the `startRenderThread` thread just died, and nothing happens afterwards.

Any idea if this is a misconfiguration on my side? Can I debug this?

System:
- Arch Linux (Linux 5.13.9) with i3
- ghc 8.10.4, cabal 3.4.0.0

**Comment by fjvallarino** [comment]
Hi @tomsmeding!

Are you able to run other OpenGL applications? Running `glxinfo` could help check if all works fine. Your driver seems to be up to date; I was checking this [thread](https://bbs.archlinux.org/viewtopic.php?pid=1776862#p1776862) that suggests running `pacman -Syu`,  but you've probably already done that.

**Comment by tomsmeding** [comment]
@fjvallarino `glxinfo` outputs lots of stuff and then exits with code 0; `glxgears` shows me some spinning gears. `glxgears -info` shows me that it's indeed running on my nvidia card. I had done a full system update recently but did it again to be sure, no change; I recompiled the world using GHC 8.10.6 and no change.

**Comment by fjvallarino** [comment]
I'm looking for clues regarding what could be happening (there are quite a few instances of that error message on Google!). 

I have this [minimal example](https://github.com/fjvallarino/sdl-continuous-resize) I created to test threaded rendering (needed to be able to keep rendering while the window is resized). Maybe it's easier to debug? The _important_ moments area [this](https://github.com/fjvallarino/sdl-continuous-resize/blob/main/src/Main.hs#L41) and [this](https://github.com/fjvallarino/sdl-continuous-resize/blob/main/src/Main.hs#L59). The workflow for creating contexts and performing rendering is the same as in the library itself.

**Comment by tomsmeding** [comment]
@fjvallarino That project fails with the exact same error. I also tried using stack instead of cabal (which is made difficult by the fact that stack bundles an old version of c2hs that isn't compatible with my system's gcc 11, or something, meaning I have to laboriously convince it to use gcc 10), but that fails in the same way again.

I'll try debugging this some, but no guarantees.

**Comment by tomsmeding** [comment]
@fjvallarino This is a modification of `Main.hs` of https://github.com/fjvallarino/sdl-continuous-resize: https://paste.tomsmeding.com/ai3lXJdj. With `doTHREADED = True` it should be equivalent to the original code; with `doTHREADED = False` it doesn't have the eventloop/renderloop thread separation and just runs the loops interlocked on one thread.

With `doTHREADED = True` it errors for me with the `glMakeCurrent` error, just like the original `sdl-continuous-resize` project did. With `doTHREADED = False` it works fine for me. (Though that single `waitEvent` should really be `pollEvents` in this case to keep the app going when many events occur, but that's an unrelated, easily fixed issue.)

While this doesn't yet indicate what exactly goes wrong, it does strongly suggest that it's got to do with the separation of the render thread. I wonder if it's just the nvidia driver acting up with separate render threads, but maybe that's paranoia.

**Comment by fjvallarino** [comment]
@tomsmeding that's really interesting! I would think it's a driver issue too. I'll see how I can fit this into the library. I think it will most likely need to be a build flag to choose between single-threaded or multithreaded (unless I can somehow detect if the application invoking the library is built with `-threaded`).

The rendering code ran in the main thread earlier, but that made it impossible to safely update the screen while resizing (unless the application is single-threaded). The content stretching while resizing caused a bad impression on almost everybody I showed the examples to, which made me change my original stance on it being a non-issue.

Just in case you still want to try the library, you can change this [forkOS](https://github.com/fjvallarino/monomer/blob/main/src/Monomer/Main/Core.hs#L197) to `forkIO`. You will also need to update `package.yaml` to remove the `-threaded` flag from the executables you want to try (otherwise, you'll get a crash sooner than later). In my experience, I had to run `stack clean` whenever I changed the threaded flags for them to be considered.

Thanks for taking the time to test this!

**Comment by tomsmeding** [comment]
That indeed works for me. It would be kind of sad, though, if it wasn't possible to make a GUI with monomer for a Haskell app that uses the threaded runtime; there are more things that need the threaded runtime, for example certain FFI-using functionality I believe.

I'll be busy the coming weeks and might not have more time to look at this. In any case, thanks for the good work. :)

**Comment by fjvallarino** [comment]
@tomsmeding just in case, I pushed new changes; I have not created a new Hackage version yet, since there are issues with a dependency that I want to solve first.

This change, commit 3993c1ca418e285f6401bfc2b99b8ef22f254088, adds a new application config option named `appRenderOnMainThread` that avoids creating a separate rendering thread. It has the disadvantage that continuous resizing will not work, but you should not get the driver error if you use it; it does not require disabling the threaded runtime. Funny enough, continuous resize still seems to work on Ubuntu when applying that config (not on macOS or Windows).

If you ever get the chance to try it, please let me know if it works for you! Thanks!

**Comment by tomsmeding** [comment]
Seems to work! Awesome :)

**Comment by fjvallarino** [comment]
@tomsmeding thanks for reporting this!

I'll close the issue. If you consider something is missing, feel free to reopen it or create a new one. Thanks!
